/* RuVKompendium 7 – offline-first, dependency-free, GitHub Pages friendly */
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={category:'Alle',query:'',limit:18};
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[+&/–—-]/g,' ').replace(/[^a-z0-9äöü ]/g,' ').replace(/\s+/g,' ').trim();
const synonyms={
  phv:['privathaftpflicht'],haftpflicht:['privathaftpflicht'],bu:['berufsunfahigkeit'],sbu:['berufsunfahigkeit'],du:['dienstunfahigkeit'],gf:['grundfahigkeit'],
  kfz:['auto','autoversicherung','kfzpolice','fahrzeug'],pkw:['auto','kfz'],pkv:['private krankenversicherung','vollversicherung'],kv:['krankenversicherung'],
  zahn:['zahnersatz','zahnzusatz'],wg:['wohngebaeude','gebaeude'],hr:['hausrat'],rs:['rechtsschutz'],avb:['bedingungen','bedingungswerk','verbraucherinformation'],
  elementar:['naturgefahren','hochwasser','starkregen','ueberschwemmung'],fahrrad:['bike','pedelec','fahrraddiebstahl'],gestohlen:['diebstahl','einbruch'],verloren:['verlust','schluesselverlust'],
  reiseruecktritt:['reise','reiseruecktritt'],ratenschutz:['restschuld','restschuldversicherung','kredit'],restschuld:['ratenschutzpolice','kreditschutz'],
  foerderbahr:['pflege bahr','pflege foerderbahr','pkb'],pflegebahr:['pflege foerderbahr','pkb'],bahr:['pflege foerderbahr','pkb'],
  zeitwertkonto:['lebensarbeitszeitkonto','wertguthaben'],lebensarbeitszeitkonto:['zeitwertkonto','wertguthaben'],
  student:['berufsunfahigkeit','privathaftpflicht','unfall'],studenten:['berufsunfahigkeit','privathaftpflicht'],familie:['haftpflicht','hausrat','risikoleben'],
  hausbesitzer:['wohngebaude','haus grundbesitzerhaftpflicht','privatrechtsschutz'],eigenheim:['wohngebaude'],beamte:['dienstunfahigkeit','krankenversicherung'],
  selbststandig:['berufsunfahigkeit','krankentagegeld','altersvorsorge'],selbststaendig:['berufsunfahigkeit','krankentagegeld','altersvorsorge'],schluessel:['schluesselverlust','privathaftpflicht'],solar:['photovoltaik','pv']
};
const alternatives=t=>[t,...(synonyms[t]||[])].map(norm).filter(Boolean);
function editDistance(a,b){if(Math.abs(a.length-b.length)>1)return 99;const row=[...Array(b.length+1).keys()];for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old;}}return row[b.length]}
function textHit(hay,alt){if(!alt)return 0;const words=hay.split(' '),need=alt.split(' ');if(need.length===1&&alt.length<=3)return words.includes(alt)?10:0;if(hay.includes(alt))return 8;if(need.length>1)return need.every(n=>words.some(w=>w.startsWith(n)))?6:0;return words.some(w=>w.startsWith(alt))?6:alt.length>=5&&words.some(w=>Math.abs(w.length-alt.length)<=1&&editDistance(w,alt)<=1)?4:0}
function evidenceFor(p,anchor){return (EVIDENCE[p.id]||[]).filter(e=>!anchor||e.anchor===anchor)}
function evidenceButton(p,anchor){const n=evidenceFor(p,anchor).length;return n?`<button class="evidence-btn" type="button" data-product="${p.id}" data-anchor="${anchor}" aria-label="Quellenbeleg anzeigen" title="Quellenbeleg anzeigen"><span>⌑</span><b>${n>1?n:''}</b></button>`:''}
function searchable(p){const ev=(EVIDENCE[p.id]||[]).map(e=>`${e.label} ${e.kind} ${e.source} ${e.code} ${e.location} ${e.text}`).join(' ');return norm([p.name,p.category,p.subcategory,p.summary,p.aliases?.join(' '),p.highlights?.join(' '),p.eligibility?.join(' '),p.addons?.join(' '),p.tariffs?.map(t=>`${t.name} ${t.code||''} ${t.note||''}`).join(' '),p.docs?.map(d=>d.label).join(' '),ev].join(' '));}
function parseQuery(raw){const filters={};const text=[];const clean=(raw||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[+&/–—-]/g,' ').replace(/[^a-z0-9äöü :]/g,' ').replace(/\s+/g,' ').trim();clean.split(' ').filter(Boolean).forEach(t=>{const m=t.match(/^(tarif|doc|baustein|kategorie|kat):(.+)$/);if(m)filters[m[1]]=norm(m[2]);else text.push(norm(t));});return{filters,text}}
function score(p,raw){if(!raw)return p.featured?80:20;const hay=searchable(p),name=norm(p.name),nameWords=name.split(' '),sub=norm(p.subcategory),cat=norm(p.category),q=parseQuery(raw);let s=0,matched=0;for(const tok of q.text){let best=0;for(const alt of alternatives(tok)){let hit=textHit(hay,alt);if(alt.length>3&&name.startsWith(alt))hit=Math.max(hit,36);else if(alt.length>3&&name.includes(alt))hit=Math.max(hit,24);else if(alt.length<=3&&nameWords.includes(alt))hit=Math.max(hit,24);if(alt.length>3&&sub.includes(alt))hit=Math.max(hit,14);if(alt.length>3&&cat.includes(alt))hit=Math.max(hit,12);best=Math.max(best,hit);}if(best){matched++;s+=best;}}
  if(q.text.length&&!matched)return-1;if(q.text.length>1&&matched/q.text.length<.5)return-1;
  if(q.filters.tarif&&!norm(p.tariffs?.map(t=>t.name).join(' ')).includes(q.filters.tarif))return-1;
  if(q.filters.baustein&&!norm(p.addons?.join(' ')).includes(q.filters.baustein))return-1;
  if(q.filters.doc&&!(p.docs?.length&&(q.filters.doc==='avb'||norm(p.docs.map(d=>d.label).join(' ')).includes(q.filters.doc))))return-1;
  if((q.filters.kategorie||q.filters.kat)&&!norm(p.category).includes(q.filters.kategorie||q.filters.kat))return-1;
  return s+(p.featured?8:0)}
function filtered(){return PRODUCTS.filter(p=>state.category==='Alle'||p.category===state.category).map(p=>({p,s:score(p,state.query)})).filter(x=>x.s>=0).sort((a,b)=>b.s-a.s||a.p.subcategory.localeCompare(b.p.subcategory)||a.p.name.localeCompare(b.p.name)).slice(0,state.limit).map(x=>x.p)}
function chip(label,count){return `<button class="chip ${state.category===label?'active':''}" data-cat="${label}">${label}<span style="opacity:.55"> · ${count}</span></button>`}
function renderFilters(){const cats=['Alle','Komposit','Leben','Kranken'];$('#categoryFilters').innerHTML=cats.map(c=>chip(c,c==='Alle'?PRODUCTS.length:PRODUCTS.filter(p=>p.category===c).length)).join('');$$('.chip').forEach(b=>b.onclick=()=>setCategory(b.dataset.cat));}
function card(p){const ev=(EVIDENCE[p.id]||[]).length;const isBrief=!(p.tariffs?.length||p.addons?.length||p.highlights?.length);const tags=[...(p.tariffs||[]).map(t=>t.name),...(p.addons?.length?['Bausteine']:[]),...(p.docs?.length?['AVB']:[])].slice(0,5);return `<button class="card" data-id="${p.id}" style="--accent:${p.category==='Leben'?'#5ab9e8':p.category==='Kranken'?'#70ddad':'#4eaad5'}"><div class="card-top"><div><span class="mini-label">${p.category} · ${p.subcategory}</span><h3>${p.name}</h3><p>${p.summary}</p></div><span class="arrow">›</span></div><div class="tags">${tags.map(t=>`<span class="tag ${/premium/i.test(t)?'premium':/AVB/.test(t)?'doc':''}">${t}</span>`).join('')}${ev?`<span class="tag evidence-tag">⌑ ${ev} Quellenbelege</span>`:isBrief?'<span class="tag brief-tag">Kurzprofil</span>':''}</div></button>`}
function render(){const items=filtered();$('#resultTitle').textContent=state.query?`Treffer für „${state.query}”`:state.category==='Alle'?'Empfohlene Einstiege':state.category;$('#resultCount').textContent=`${items.length}${items.length===state.limit?'+':''} TREFFER`;$('#results').innerHTML=items.length?items.map(card).join(''):`<div class="empty"><strong>Noch kein Treffer.</strong>Versuche einen Oberbegriff, ein Kürzel wie BU/PKV/PHV oder tippe nur den Anfang.</div>`;$$('.card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id));}
function setCategory(c){state.category=c;state.limit=18;renderFilters();$$('.dock-btn').forEach(b=>b.classList.toggle('active',b.dataset.cat===c||(c==='Alle'&&b.dataset.cat==='Alle')));render();if(c!=='Alle')window.scrollTo({top:260,behavior:'smooth'});}
function openDetail(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const evCount=(EVIDENCE[p.id]||[]).length;const isBrief=!(p.tariffs?.length||p.addons?.length||p.highlights?.length||p.eligibility?.length);const eligibility=p.eligibility?.length?`<h3 class="section-title">Abschluss & Grenzen</h3><div class="fact-grid eligibility-grid">${p.eligibility.map((x,i)=>`<div class="fact evidence-row eligibility-fact"><span>${x}</span>${evidenceButton(p,`eligibility:${i}`)}</div>`).join('')}</div>`:'';const tariffs=p.tariffs?.length?`<h3 class="section-title">Tarife / Varianten</h3><div class="tariff-grid">${p.tariffs.map(t=>`<div class="tariff"><div class="evidence-row"><strong>${t.name}<span>${t.code||''}</span></strong>${evidenceButton(p,`tariff:${norm(t.name)}`)}</div><p>${t.note||'Siehe vereinbarte Bedingungen.'}</p></div>`).join('')}</div>`:'';const addons=p.addons?.length?`<h3 class="section-title">Zusatzbausteine / Optionen</h3><div class="addon-list">${p.addons.map(a=>`<span class="addon"><span>${a}</span>${evidenceButton(p,`addon:${norm(a)}`)}</span>`).join('')}</div>`:'';const facts=p.highlights?.length?`<h3 class="section-title">Berater-Schnellcheck</h3><div class="fact-grid">${p.highlights.map((x,i)=>`<div class="fact evidence-row"><span>${x}</span>${evidenceButton(p,`highlight:${i}`)}</div>`).join('')}</div>`:'';const brief=isBrief?'<div class="profile-note"><strong>Kurzprofil</strong><span>Für diesen Beratungsweg sind bewusst keine pauschalen Tarifwerte hinterlegt. Bitte Leistungsumfang im zugeordneten Bedingungswerk bzw. auf der aktuellen Produktseite prüfen.</span></div>':'';const docs=p.docs?.length?`<h3 class="section-title">Bedingungswerke</h3>${p.docs.map(d=>`<a class="source-button secondary" href="${d.url}" target="_blank" rel="noopener"><span>${d.label}</span><b>↗</b></a>`).join('')}`:'';$('#detailContent').innerHTML=`<div class="detail-hero"><p class="eyebrow">${p.category} · ${p.subcategory}</p><h2>${p.name}</h2><p>${p.summary}</p>${evCount?`<div class="evidence-summary"><span>⌑</span><strong>${evCount} Quellenbelege</strong><small>direkt offline lesbar</small></div>`:''}</div>${eligibility}${facts}${tariffs}${addons}${brief}${docs}<h3 class="section-title">R+V Quelle</h3><a class="source-button" href="${p.url}" target="_blank" rel="noopener"><span>Aktuelle Produktseite öffnen</span><b>↗</b></a><div class="notice">Schnellübersicht, Stand 08.08.2026. Maßgeblich sind der konkrete Vertrag und die darin vereinbarten Bedingungen.</div>`;$('#detailDialog').showModal();}
function openEvidence(productId,anchor){const p=PRODUCTS.find(x=>x.id===productId);const list=p?evidenceFor(p,anchor):[];if(!p||!list.length)return;$('#evidenceTitle').textContent=list.length===1?list[0].label:`${p.name} · Quellen`;$('#evidenceContent').innerHTML=list.map(e=>`<article class="evidence-card"><div class="evidence-card-head"><span class="evidence-kind ${e.kind.startsWith('Bedingungswerk')?'avb':'web'}">${e.kind}</span><span class="evidence-check">GEPRÜFT ${EVIDENCE_META.checked}</span></div><h3>${e.source}</h3><div class="evidence-meta"><strong>${e.code}</strong><span>${e.location}</span></div>${e.quote?`<blockquote>„${e.quote}“</blockquote>`:''}<p class="evidence-text">${e.text}</p></article>`).join('');$('#evidenceDialog').showModal();}
function init(){renderFilters();const evTotal=Object.values(EVIDENCE).reduce((n,a)=>n+a.length,0);$('#stats').innerHTML=`<div class="stat"><strong>${PRODUCTS.length}</strong><span>Produktwege</span></div><div class="stat"><strong>${PRODUCTS.reduce((n,p)=>n+(p.tariffs?.length||0),0)}</strong><span>Tarife</span></div><div class="stat"><strong>${evTotal}</strong><span>Quellenbelege</span></div>`;$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;state.limit=30;$('#clearBtn').style.display=state.query?'block':'none';render()});$('#clearBtn').onclick=()=>{$('#searchInput').value='';state.query='';$('#clearBtn').style.display='none';render();$('#searchInput').focus()};$$('.search-hints button').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.query;state.query=b.dataset.query;render()});$$('.dock-btn').forEach(b=>b.onclick=()=>{if(b.dataset.cat==='Alle'){$('#searchInput').focus();setCategory('Alle')}else setCategory(b.dataset.cat)});$('#homeBtn').onclick=()=>{state.query='';$('#searchInput').value='';setCategory('Alle');scrollTo({top:0,behavior:'smooth'})};$('#detailClose').onclick=()=>$('#detailDialog').close();$('#detailDialog').onclick=e=>{const b=e.target.closest('.evidence-btn');if(b){e.preventDefault();e.stopPropagation();openEvidence(b.dataset.product,b.dataset.anchor);return}if(e.target===$('#detailDialog'))$('#detailDialog').close()};$('#evidenceClose').onclick=()=>$('#evidenceDialog').close();$('#evidenceDialog').onclick=e=>{if(e.target===$('#evidenceDialog'))$('#evidenceDialog').close()};$('#infoBtn').onclick=()=>$('#infoDialog').showModal();$('#infoClose').onclick=()=>$('#infoDialog').close();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render()}
init();
