/* RuVKompendium 1 – offline-first, dependency-free, GitHub Pages friendly */
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={category:'Alle',query:'',limit:18};
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[+&/–—-]/g,' ').replace(/[^a-z0-9äöüß ]/g,' ').replace(/\s+/g,' ').trim();
const synonyms={phv:'privathaftpflicht',haftpflicht:'haftpflicht',bu:'berufsunfahigkeit',sbu:'berufsunfahigkeit',du:'dienstunfahigkeit',gf:'grundfahigkeit',kfz:'auto fahrzeug',pkw:'auto',pkv:'private krankenversicherung',kv:'krankenversicherung',zahn:'zahnersatz',wg:'wohngebaude',hr:'hausrat',rs:'rechtsschutz',avb:'bedingungen bedingungswerk',elementar:'naturgefahren',fahrrad:'bike pedelec',reiserucktritt:'reise'};
const expandToken=t=>`${t} ${synonyms[t]||''}`.trim();
function searchable(p){return norm([p.name,p.category,p.subcategory,p.summary,p.aliases?.join(' '),p.highlights?.join(' '),p.addons?.join(' '),p.tariffs?.map(t=>`${t.name} ${t.code||''} ${t.note||''}`).join(' '),p.docs?.map(d=>d.label).join(' ')].join(' '));}
function parseQuery(raw){const filters={};const text=[];const clean=(raw||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[+&/–—-]/g,' ').replace(/[^a-z0-9äöüß :]/g,' ').replace(/\s+/g,' ').trim();clean.split(' ').filter(Boolean).forEach(t=>{const m=t.match(/^(tarif|doc|baustein|kategorie|kat):(.+)$/);if(m)filters[m[1]]=m[2];else text.push(expandToken(t));});return{filters,text:text.join(' ').split(' ').filter(Boolean)}}
function score(p,raw){if(!raw)return p.featured?80:20;const hay=searchable(p);const q=parseQuery(raw);let s=0;for(const tok of q.text){if(norm(p.name).startsWith(tok))s+=36;else if(norm(p.name).includes(tok))s+=24;if(norm(p.subcategory).includes(tok))s+=14;if(norm(p.category).includes(tok))s+=12;if(hay.includes(tok))s+=8;else return -1;}if(q.filters.tarif&&!norm(p.tariffs?.map(t=>t.name).join(' ')).includes(q.filters.tarif))return-1;if(q.filters.baustein&&!norm(p.addons?.join(' ')).includes(q.filters.baustein))return-1;if(q.filters.doc&&!(p.docs?.length&&(q.filters.doc==='avb'||norm(p.docs.map(d=>d.label).join(' ')).includes(q.filters.doc))))return-1;if((q.filters.kategorie||q.filters.kat)&&!norm(p.category).includes(q.filters.kategorie||q.filters.kat))return-1;return s+(p.featured?8:0)}
function filtered(){return PRODUCTS.filter(p=>state.category==='Alle'||p.category===state.category).map(p=>({p,s:score(p,state.query)})).filter(x=>x.s>=0).sort((a,b)=>b.s-a.s||a.p.subcategory.localeCompare(b.p.subcategory)||a.p.name.localeCompare(b.p.name)).slice(0,state.limit).map(x=>x.p)}
function chip(label,count){return `<button class="chip ${state.category===label?'active':''}" data-cat="${label}">${label}<span style="opacity:.55"> · ${count}</span></button>`}
function renderFilters(){const cats=['Alle','Komposit','Leben','Kranken'];$('#categoryFilters').innerHTML=cats.map(c=>chip(c,c==='Alle'?PRODUCTS.length:PRODUCTS.filter(p=>p.category===c).length)).join('');$$('.chip').forEach(b=>b.onclick=()=>setCategory(b.dataset.cat));}
function card(p){const tags=[...(p.tariffs||[]).map(t=>t.name),...(p.addons?.length?['Bausteine']:[]),...(p.docs?.length?['AVB']:[])].slice(0,5);return `<button class="card" data-id="${p.id}" style="--accent:${p.category==='Leben'?'#5ab9e8':p.category==='Kranken'?'#70ddad':'#4eaad5'}"><div class="card-top"><div><span class="mini-label">${p.category} · ${p.subcategory}</span><h3>${p.name}</h3><p>${p.summary}</p></div><span class="arrow">›</span></div><div class="tags">${tags.map(t=>`<span class="tag ${/premium/i.test(t)?'premium':/AVB/.test(t)?'doc':''}">${t}</span>`).join('')}</div></button>`}
function render(){const items=filtered();$('#resultTitle').textContent=state.query?`Treffer für „${state.query}”`:state.category==='Alle'?'Empfohlene Einstiege':state.category;$('#resultCount').textContent=`${items.length}${items.length===state.limit?'+':''} TREFFER`;$('#results').innerHTML=items.length?items.map(card).join(''):`<div class="empty"><strong>Noch kein Treffer.</strong>Versuche einen Oberbegriff, ein Kürzel wie BU/PKV/PHV oder tippe nur den Anfang.</div>`;$$('.card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id));}
function setCategory(c){state.category=c;state.limit=18;renderFilters();$$('.dock-btn').forEach(b=>b.classList.toggle('active',b.dataset.cat===c||(c==='Alle'&&b.dataset.cat==='Alle')));render();if(c!=='Alle')window.scrollTo({top:260,behavior:'smooth'});}
function openDetail(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const tariffs=p.tariffs?.length?`<h3 class="section-title">Tarife / Varianten</h3><div class="tariff-grid">${p.tariffs.map(t=>`<div class="tariff"><strong>${t.name}<span>${t.code||''}</span></strong><p>${t.note||'Siehe vereinbarte Bedingungen.'}</p></div>`).join('')}</div>`:'';const addons=p.addons?.length?`<h3 class="section-title">Zusatzbausteine / Optionen</h3><div class="addon-list">${p.addons.map(a=>`<span class="addon">${a}</span>`).join('')}</div>`:'';const facts=p.highlights?.length?`<h3 class="section-title">Berater-Schnellcheck</h3><div class="fact-grid">${p.highlights.map(x=>`<div class="fact">${x}</div>`).join('')}</div>`:'';const docs=p.docs?.length?`<h3 class="section-title">Bedingungswerke</h3>${p.docs.map(d=>`<a class="source-button secondary" href="${d.url}" target="_blank" rel="noopener"><span>${d.label}</span><b>↗</b></a>`).join('')}`:'';$('#detailContent').innerHTML=`<div class="detail-hero"><p class="eyebrow">${p.category} · ${p.subcategory}</p><h2>${p.name}</h2><p>${p.summary}</p></div>${facts}${tariffs}${addons}${docs}<h3 class="section-title">R+V Quelle</h3><a class="source-button" href="${p.url}" target="_blank" rel="noopener"><span>Aktuelle Produktseite öffnen</span><b>↗</b></a><div class="notice">Schnellübersicht, Stand 08.08.2026. Maßgeblich sind der konkrete Vertrag und die darin vereinbarten Bedingungen.</div>`;$('#detailDialog').showModal();}
function init(){renderFilters();$('#stats').innerHTML=`<div class="stat"><strong>${PRODUCTS.length}</strong><span>Produktwege</span></div><div class="stat"><strong>${PRODUCTS.reduce((n,p)=>n+(p.tariffs?.length||0),0)}</strong><span>Tarife</span></div><div class="stat"><strong>${new Set(PRODUCTS.flatMap(p=>(p.docs||[]).map(d=>d.url))).size}</strong><span>AVB-Quellen</span></div>`;$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;state.limit=30;$('#clearBtn').style.display=state.query?'block':'none';render()});$('#clearBtn').onclick=()=>{$('#searchInput').value='';state.query='';$('#clearBtn').style.display='none';render();$('#searchInput').focus()};$$('.search-hints button').forEach(b=>b.onclick=()=>{$('#searchInput').value=b.dataset.query;state.query=b.dataset.query;render()});$$('.dock-btn').forEach(b=>b.onclick=()=>{if(b.dataset.cat==='Alle'){$('#searchInput').focus();setCategory('Alle')}else setCategory(b.dataset.cat)});$('#homeBtn').onclick=()=>{state.query='';$('#searchInput').value='';setCategory('Alle');scrollTo({top:0,behavior:'smooth'})};$('#detailClose').onclick=()=>$('#detailDialog').close();$('#detailDialog').onclick=e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()};$('#infoBtn').onclick=()=>$('#infoDialog').showModal();$('#infoClose').onclick=()=>$('#infoDialog').close();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render()}
init();
