/* Datenbasis: öffentliche R+V-Webseiten und Bedingungszentrale, geprüft 08.08.2026. */
const DOCS={
  avb:'https://www.ruv.de/service/weitere-services/versicherungsbedingungen',
  classic:'https://www.ruv.de/dam/jcr%3A41df7b64-f3f4-48be-9230-0a74d7760284/ruv-kpr_privatkunden_verbraucherinfo.PDF',
  comfort:'https://www.ruv.de/dam/jcr%3A536cbb74-a0e6-47d3-be55-f2d2860f5030/ruv-kpp-privatkunden-privatpolice-comfort-verbraucherinfo.2026-06-29-14-56-43.pdf',
  premium:'https://www.ruv.de/dam/jcr%3A454128d9-56f7-424c-a705-81bbdf4d8f31/privatkunden-verbraucherinformation-hausrat-haftpflicht-premium.pdf',
  kfz:'https://www.ruv.de/dam/jcr%3A697df30d-36c9-478f-a8a0-f1783b7843e1/Verbraucherinformation_RVA_Pkw_01.07.2026.2.0103953fd58738a3d6f27ae424bc3291.pdf',
  kfzOther:'https://www.ruv.de/dam/jcr%3Af353bb0b-7a8f-423e-8520-78e051971d79/Verbraucherinformation_RVA_Nicht-Pkw_01.07.2026.2.3cc4eb95414874f986f5d82467e2e30d.pdf',
  leben:'https://www.ruv.de/dam/jcr%3A038d2022-558e-46d7-b161-e37647ff9a2d/PLG0426.2026-04-30-12-59-13.pdf',
  risiko:'https://www.ruv.de/dam/jcr/privatkunden/downloads/versicherungsbedingungen/risikoleben-avb.pdf',
  kranken:'https://www.ruv.de/dam/jcr%3A266e323c-c558-4fa0-a67f-820016db0dd9/ruv-pkx_kranken_verbraucherinfo.pdf',
  unfall:'https://www.ruv.de/dam/jcr%3A14f4d452-1ae5-455d-8692-2adbf8f8429b/PUR0122.2026-01-20-10-56-01.PDF',
  kapitalUnfall:'https://www.ruv.de/dam/jcr%3A28f8bae4-36c3-4d94-95f2-4ba5eef3c1cc/kapital-unfallversicherung-avb-0122.2026-06-23-16-31-27.pdf',
  hundOp:'https://www.ruv.de/dam/jcr%3Ab8a71fdc-2ee5-4c21-bd54-7f56ff63579a/opk-hund-avb-erweitert.2026-06-19-09-18-12.pdf',
  pferdOp:'https://www.ruv.de/dam/jcr%3A99b0715a-b65a-40de-be08-d970a9659f5e/OPK_Pferd_AVB.2023-07-03-11-17-35.pdf'
};
const D=(label,url)=>({label,url});
const T=(name,code,note)=>({name,code,note});
const P=(id,name,category,subcategory,summary,url,extra={})=>({id,name,category,subcategory,summary,url,...extra});
const CP=[D('PrivatPolice classic – Verbraucherinformation 07/2026',DOCS.classic),D('PrivatPolice comfort – Verbraucherinformation 07/2026',DOCS.comfort),D('PrivatPolice premium – Verbraucherinformation 07/2026',DOCS.premium)];
const KV=[D('Bedingungsheft R+V Krankenversicherung AG (PKX 07/26)',DOCS.kranken)];
const LV=[D('Bedingungsheft R+V Lebensversicherung AG (PLG 04/26)',DOCS.leben)];
const KFV=[D('Kfz-Verbraucherinformation Pkw – Stand 01.07.2026',DOCS.kfz)];
const KFO=[D('Kfz-Verbraucherinformation Nicht-Pkw – Stand 01.07.2026',DOCS.kfzOther)];

const PRODUCTS=[
  P('kfz-auto','Autoversicherung / R+V-KfzPolice','Komposit','Kfz','Haftpflicht, Teil- oder Vollkasko mit drei Produktvarianten und modularen Zusatzbausteinen.','https://www.ruv.de/kfz-versicherung/autoversicherung',{featured:true,aliases:['Auto','Pkw','KfzPolice','Vollkasko','Teilkasko'],tariffs:[T('classic','','KH: 100 Mio. EUR pauschal; Personenschäden 12 Mio. EUR. TK-Neupreis bis 12 Monate.'),T('comfort','','KH: 100 Mio. EUR; Personenschäden 15 Mio. EUR. Erweiterte Kaskoleistungen.'),T('premium','','KH: 100 Mio. EUR; Personenschäden 16 Mio. EUR; Umweltschaden bis 100 Mio. EUR; erweiterte Kasko.')],addons:['Fahrerschutz','Werkstattservice','Werkstattservice Glas','Schutzbrief','GAP/Differenzdeckung','Rabattschutz','Kasko-Extra','Kasko Spezial','Zusatzfahrer'],highlights:['Kfz-Haftpflicht ist Pflicht; Teil- und Vollkasko sind freiwillige Ergänzungen.','Neupreisentschädigung laut Produktseite je Variante bis zu 30 Monate.','Fahrerschutz: 32,90 EUR/Jahr; Schutzbrief: 19,90 EUR/Jahr (Produktseite, Stand 08.08.2026).'],docs:KFV}),
  P('kfz-eauto','E-Autoversicherung','Komposit','Kfz · Elektromobilität','Kfz-Schutz für Elektro-Pkw mit auf E-Mobilität zugeschnittenen Leistungen.','https://www.ruv.de/kfz-versicherung/e-auto-versicherung',{aliases:['Elektroauto','E Auto','Akku','Wallbox'],docs:KFV}),
  P('kfz-zweitwagen','Zweitwagenversicherung','Komposit','Kfz','Versicherung eines weiteren Pkw; Einstufung und Beitrag hängen von der individuellen Konstellation ab.','https://www.ruv.de/kfz-versicherung/zweitwagenversicherung',{aliases:['Zweitwagen'],docs:KFV}),
  P('kfz-motorrad','Motorradversicherung','Komposit','Kfz · Zweirad','Haftpflicht und wahlweise Kaskoschutz für Motorräder.','https://www.ruv.de/kfz-versicherung/motorradversicherung',{aliases:['Motorrad','Bike'],docs:KFO}),
  P('kfz-125','125-ccm-Versicherung','Komposit','Kfz · Zweirad','Versicherung für Leichtkrafträder bis 125 ccm im R+V-Kfz-Angebot.','https://www.ruv.de/kfz-versicherung/125-ccm-versicherung',{aliases:['125er','Leichtkraftrad'],docs:KFO}),
  P('kfz-roller','Rollerversicherung','Komposit','Kfz · Zweirad','Kfz-Schutz für Roller; je Fahrzeugklasse Versicherungskennzeichen oder reguläre Zulassung.','https://www.ruv.de/kfz-versicherung/roller-versicherung',{aliases:['Roller'],docs:KFO}),
  P('kfz-moped','Mopedversicherung','Komposit','Kfz · Versicherungskennzeichen','Haftpflichtschutz für Moped, Mofa und weitere kennzeichenpflichtige Kleinfahrzeuge.','https://www.ruv.de/kfz-versicherung/moped-versicherung',{aliases:['Moped','Mofa','Versicherungskennzeichen'],docs:[D('Bedingungszentrale – Fahrzeuge mit Versicherungskennzeichen',DOCS.avb)]}),
  P('kfz-escooter','E-Scooter-Versicherung','Komposit','Kfz · Elektromobilität','Haftpflichtschutz mit Versicherungskennzeichen für E-Scooter.','https://www.ruv.de/kfz-versicherung/moped-versicherung/e-scooter',{aliases:['E Scooter','Elektrokleinstfahrzeug'],docs:[D('Bedingungszentrale – Versicherungskennzeichen',DOCS.avb)]}),
  P('kfz-ebike','E-Bike-Versicherung','Komposit','Kfz · Elektromobilität','R+V-Schutz für versicherungspflichtige E-Bikes/S-Pedelecs im Mobilitätsangebot.','https://www.ruv.de/kfz-versicherung/moped-versicherung/e-bike',{aliases:['E Bike','S Pedelec','Pedelec'],docs:[D('Bedingungszentrale – Versicherungskennzeichen',DOCS.avb)]}),
  P('kfz-quad','Quad-Versicherung','Komposit','Kfz','Haftpflicht- und Kaskolösungen für Quads.','https://www.ruv.de/kfz-versicherung/quad-versicherung',{aliases:['Quad','ATV'],docs:KFO}),
  P('kfz-wohnmobil','Wohnmobilversicherung','Komposit','Kfz · Camping','Kfz-Versicherung für Wohnmobile mit Haftpflicht und optionaler Kasko.','https://www.ruv.de/kfz-versicherung/wohnmobil-versicherung',{aliases:['Wohnmobil','Camper'],docs:KFO}),
  P('kfz-wohnwagen','Wohnwagenversicherung','Komposit','Kfz · Camping','Versicherungslösung für Wohnwagen/Caravans.','https://www.ruv.de/kfz-versicherung/wohnwagenversicherung',{aliases:['Wohnwagen','Caravan'],docs:KFO}),
  P('kfz-anhaenger','Anhänger-Versicherung','Komposit','Kfz','Kfz-Haftpflichtschutz für zulassungspflichtige Anhänger, optional je Risiko ergänzbar.','https://www.ruv.de/kfz-versicherung/anhaenger-versicherung',{aliases:['Anhänger'],docs:KFO}),

  P('hausrat','Hausratversicherung','Komposit','Haus & Wohnen','Neuwertschutz für privaten Hausrat gegen u. a. Feuer, Leitungswasser, Sturm/Hagel, Einbruch, Raub und Vandalismus.','https://www.ruv.de/hausratversicherung',{featured:true,aliases:['HausratPolice','HR'],tariffs:[T('classic','HRB 07/2026','Basisstufe; Außenversicherung 6 Monate bis 20.000 EUR, Bargeld bis 1.500 EUR.'),T('comfort','HRB 07/2026','Erweitert; Außenversicherung 12 Monate bis 30.000 EUR, Bargeld bis 2.000 EUR.'),T('premium','HRB 07/2026','Stärkster Schutz; Außenversicherung 12 Monate bis 100.000 EUR, Bargeld bis 5.000 EUR, Versehensschutz bis 5.000 EUR bei 500 EUR SB.')],addons:['Glasbruch','Fahrraddiebstahl','Fahrrad Plus','Naturgefahren Plus','Hausrat auf Reisen','SicherOnline','SofortHilfe','KunstSpezial'],highlights:['Versicherungssumme bei korrekter Wohnfläche laut Produktseite unbegrenzt; Neuwertentschädigung.','Gartenmöbel/-geräte: classic bis 500 EUR, comfort bis 2.000 EUR, premium unbegrenzt.','Hotelkosten: classic 200 EUR/Tag max. 200 Tage; comfort 300 EUR/Tag max. 300 Tage; premium 300 EUR/Tag bis Wiederbewohnbarkeit.'],docs:CP}),
  P('hausrat-haftpflicht','Hausrat & Haftpflicht Kombi','Komposit','Haus & Wohnen','Gemeinsamer Abschluss von Hausrat- und Privathaftpflicht; Leistungsumfang folgt den jeweils gewählten Tarifvarianten.','https://www.ruv.de/hausrat-haftpflicht-kombi',{tariffs:[T('classic'),T('comfort'),T('premium')],addons:['Hausrat-Zusatzbausteine','Haftpflichtoptionen'],docs:CP}),
  P('bankschliessfach','Bankschließfachversicherung','Komposit','Haus & Wohnen','Absicherung von Werten im Bankschließfach; individuelle Versicherungssummen und laut Produktseite tägliches Kündigungsrecht.','https://www.ruv.de/bankschliessfach-versicherung',{aliases:['Schließfach','Bankschliessfach'],highlights:['Einstieg laut Produktseite ab 6,99 EUR brutto/Jahr bei 1.000 EUR Versicherungssumme; Sondertarife für Mitglieder/Mitarbeiter von Volks- und Raiffeisenbanken.'],docs:[D('Bedingungen Bankschließfachversicherung', 'https://www.ruv.de/dam/jcr%3Af97c6e42-baa1-40f4-bc5d-7611ffa43336/versicherungsbedingungen-bankschliessfachversicherung.pdf')]}),
  P('wohngebaeude','Wohngebäudeversicherung','Komposit','Haus & Wohnen','Schützt das Gebäude u. a. gegen Feuer, Leitungswasser, Sturm/Hagel und kann modular erweitert werden.','https://www.ruv.de/wohngebaeudeversicherung',{featured:true,aliases:['WG','Gebäude','Eigenheim'],tariffs:[T('classic','WGB 01/23','Preis-Leistungs-Variante; Innovationsgarantie.'),T('comfort','WGB 01/23','Größerer Leistungsumfang; zusätzliche nur hier verfügbare Bausteine.')],addons:['Naturgefahren Plus','Glasbruch','Überspannung durch Blitz','Photovoltaik','Solarthermie','Gewerblicher Mietverlust','Erhöhung Rohrpaket (comfort)','Weitere comfort-Bausteine'],highlights:['Versichert sind u. a. Haus, Carports/Garagen, elektrische und sanitäre Anlagen; Nebengebäude bis 30.000 EUR laut Produktseite.','Gas-/Wasserverlust: classic bis 300 EUR, comfort bis 2.500 EUR.','Naturgefahren Plus u. a. Überschwemmung, Starkregen, Rückstau, Erdbeben/Erdrutsch, Schneedruck/Lawinen, Vulkanausbruch; ab 500 EUR SB.'],docs:[D('classic – WGB F/S 01/23 im Verbraucherheft',DOCS.classic),D('comfort – WGB F/S 01/23 + Comfort-Zusatzbausteine',DOCS.comfort)]}),
  P('pv','Photovoltaikversicherung','Komposit','Haus & Wohnen','Privater Photovoltaikschutz als Baustein der Wohngebäudeversicherung für Anlagen bis 30 kWp.','https://www.ruv.de/erneuerbare-energien/photovoltaikversicherung',{aliases:['PV','Photovoltaik','Solar','Solaranlage','EnergiePolice'],tariffs:[T('classic','','PV-Baustein zur Wohngebäude classic; der konkrete Leistungsumfang folgt Tarif und Vereinbarung.'),T('comfort','','PV-Baustein zur Wohngebäude comfort; erweiterte Wohngebäude-Optionen bleiben separat zu prüfen.')],addons:['Ertragsausfall optional','Wohngebäude classic/comfort als Träger'],highlights:['Für private Dachanlagen bis 30 kWp als Ergänzung der R+V-Wohngebäudeversicherung.','Versicherbare Gefahren umfassen nach Produktdarstellung unter anderem Sturm/Hagel, Diebstahl, Überspannung und Tierbiss; Details regeln die Bedingungen.','Ertragsausfall kann optional eingeschlossen werden; laut Produktseite ist eine Dauer bis 180 Tage wählbar.'],docs:[D('Wohngebäude-Bedingungen classic',DOCS.classic),D('Wohngebäude comfort',DOCS.comfort)]}),
  P('mietkaution','MietkautionsBürgschaft','Komposit','Haus & Wohnen','Bürgschaft als Alternative zur Barkaution bzw. zum Kautionssparbuch.','https://www.ruv.de/mietkautionsbuergschaft',{aliases:['Mietkaution','Bürgschaft'],docs:[D('R+V-MietkautionsBürgschaft – Bedingungen',DOCS.avb)]}),
  P('sichervermieten','Mietschutzversicherung SicherVermieten','Komposit','Haus & Wohnen','Schutz für private Vermieter gegen definierte Mietrückstände, Mietausfall sowie bestimmte Sach-/Renovierungsschäden.','https://www.ruv.de/mietausfallversicherung',{aliases:['Mietschutz','Vermieter','Sicher Vermieten'],docs:[D('SicherVermieten – Bedingungen 07/26 im premium-Heft',DOCS.premium)]}),
  P('geraeteschutz','GeräteSchutz / Elektronikversicherung','Komposit','Elektronik','Versicherung für ausgewählte private Elektronikgeräte gegen versicherte Beschädigungen.','https://www.ruv.de/elektronikversicherung',{aliases:['Geräteschutz','Elektronik','Hardware','Laptop'],docs:[D('R+V-GeräteSchutz – Allgemeine Bedingungen',DOCS.avb)]}),
  P('laptop','Laptopversicherung','Komposit','Elektronik','Elektronikschutz speziell rund um Laptop/Notebook und versicherte Schäden.','https://www.ruv.de/elektronikversicherung/laptopversicherung',{aliases:['Notebook','Laptop'],docs:[D('GeräteSchutz – Bedingungen',DOCS.avb)]}),
  P('hardware','Hardwareversicherung','Komposit','Elektronik','R+V-Geräteschutz für ausgewählte Hardware als privates Elektronikrisiko.','https://www.ruv.de/elektronikversicherung/hardwareversicherung',{aliases:['Hardware','Elektronik'],docs:[D('GeräteSchutz – Bedingungen',DOCS.avb)]}),

  P('phv','Private Haftpflichtversicherung','Komposit','Haftpflicht','Wehrt unberechtigte Ansprüche ab und leistet bei versicherten Personen-, Sach- und Vermögensschäden.','https://www.ruv.de/haftpflichtversicherung/private-haftpflichtversicherung',{featured:true,aliases:['PHV','Privathaftpflicht','Schlüsselverlust','Mietsachschaden'],tariffs:[T('classic','HPB 07/26','10 Mio. EUR Versicherungssumme; weltweiter vorübergehender Aufenthalt 2 Jahre.'),T('comfort','HPB 07/26','40 Mio. EUR; u. a. Schlüsselverlust privat/beruflich bis 50.000 EUR.'),T('premium','HPB 07/26','100 Mio. EUR; u. a. Schlüsselverlust bis zur Versicherungssumme, Neuwertoptionen und Kfz-nahe Extras.')],addons:['Diensthaftpflichtrisiko (sofern vereinbart)','Weitere besondere Haftpflichtrisiken nach Vertrag'],highlights:['Mietsach- und Gefälligkeitsschäden sowie Internetschäden sind Bestandteil des beschriebenen Schutzes.','Forderungsausfall für Personen-/Sachschäden ab 1.000 EUR Mindestschaden laut Tarifübersicht.','Premium: Neuwertentschädigung bis 10.000 EUR und Sachalter bis 2 Jahre; Kfz-Be-/Entladeschäden bis 10.000 EUR.'],docs:CP}),
  P('hugb','Haus- und Grundbesitzerhaftpflicht','Komposit','Haftpflicht','Haftpflichtschutz aus Besitz/Nutzung eines Gebäudes oder Grundstücks.','https://www.ruv.de/haftpflichtversicherung/haus-und-grundbesitzerhaftpflicht',{tariffs:[T('classic','','10 Mio. EUR pauschal'),T('comfort','','40 Mio. EUR pauschal'),T('premium','','100 Mio. EUR pauschal')],docs:CP}),
  P('bauherr','Bauherrenhaftpflichtversicherung','Komposit','Haftpflicht','Schützt private Bauherren vor gesetzlichen Haftpflichtansprüchen aus dem Bauvorhaben.','https://www.ruv.de/haftpflichtversicherung/bauherrenhaftpflichtversicherung',{aliases:['Bauherr','Bauprojekt'],docs:CP}),
  P('gewaesser','Gewässerschadenhaftpflicht','Komposit','Haftpflicht','Haftpflichtschutz für private Gewässerschadenrisiken, etwa aus Anlagen mit wassergefährdenden Stoffen.','https://www.ruv.de/haftpflichtversicherung/gewaesserschadenhaftpflichtversicherung',{aliases:['Öltank','Heizöltank','Gewässer'],docs:CP}),
  P('wasserfahrzeug','Haftpflicht für private Wasserfahrzeuge','Komposit','Haftpflicht','Haftpflichtschutz für definierte private Wasserfahrzeugrisiken.','https://www.ruv.de/haftpflichtversicherung/wasserfahrzeuge',{aliases:['Boot','Segelboot','Wasserfahrzeug'],docs:CP}),
  P('jagd','Jagdhaftpflichtversicherung','Komposit','Haftpflicht','Spezielle Haftpflicht für Jäger und jagdliche Risiken.','https://www.ruv.de/haftpflichtversicherung/jagdhaftpflichtversicherung',{aliases:['Jäger','Jagd'],docs:[D('R+V HaftpflichtPolice für Jäger – Bedingungszentrale',DOCS.avb)]}),
  P('reitlehrer','Reitlehrerhaftpflichtversicherung','Komposit','Haftpflicht','Haftpflichtschutz für Reitlehrer bei versicherten Risiken aus der Tätigkeit.','https://www.ruv.de/haftpflichtversicherung/reitlehrerhaftpflicht',{aliases:['Reitlehrer','Reitunterricht'],docs:[D('Bedingungszentrale Haftpflicht',DOCS.avb)]}),

  P('recht-privat','Privat-Rechtsschutz','Komposit','Rechtsschutz','Kosten- und Beratungsabsicherung bei privaten Rechtsstreitigkeiten; modular mit Beruf, Verkehr und Immobilien kombinierbar.','https://www.ruv.de/rechtsschutzversicherung/privatrechtsschutz',{featured:true,aliases:['RS','Rechtsschutz'],tariffs:[T('classic','RSB 07/23','Versicherungssumme je Rechtsschutzfall 1 Mio. EUR; Strafkaution bis 100.000 EUR.'),T('comfort','RSB 07/23','Versicherungssumme 4 Mio. EUR; Strafkaution bis 300.000 EUR; zusätzliche Comfort-Bausteine möglich.')],addons:['Spezial-Straf-Rechtsschutz (classic/comfort)','Vorsorge Familie & Erbe (nur comfort)','Urheberrecht (nur comfort)','Kapitalanlagen (nur comfort)','Berufs-Rechtsschutz','Verkehrs-Rechtsschutz','Immobilien-Rechtsschutz'],highlights:['Selbstbeteiligung laut Produktseite wählbar: 0, 150 oder 250 EUR.','Weltweiter Internetvertragsrechtsschutz: classic bis 30.000 EUR, comfort bis 300.000 EUR.','Telefonische Erstberatung und Mediation sind als Servicebestandteile beschrieben.'],docs:[D('PrivatPolice classic – RSB 07/23',DOCS.classic),D('PrivatPolice comfort – RSB 07/23',DOCS.comfort)]}),
  P('recht-verkehr','Verkehrs-Rechtsschutz','Komposit','Rechtsschutz','Rechtsschutz für rechtliche Konflikte im Straßenverkehr, z. B. Unfall, Bußgeld oder Werkstatt.','https://www.ruv.de/rechtsschutzversicherung/verkehrsrechtsschutz',{aliases:['Verkehr','Bußgeld','Werkstatt'],docs:[D('Rechtsschutzbedingungen classic/comfort',DOCS.classic),D('comfort',DOCS.comfort)]}),
  P('recht-beruf','Berufs-Rechtsschutz','Komposit','Rechtsschutz','Rechtsschutz für arbeitsrechtliche Konflikte, etwa Abmahnung oder Aufhebungsvertrag.','https://www.ruv.de/rechtsschutzversicherung/berufsrechtsschutz',{aliases:['Arbeitsrecht','Abmahnung','Job'],docs:[D('Rechtsschutzbedingungen',DOCS.classic),D('comfort',DOCS.comfort)]}),
  P('recht-immo','Immobilien-Rechtsschutz','Komposit','Rechtsschutz','Rechtsschutz für Eigentümer, Mieter und Pächter bei definierten Immobilienkonflikten.','https://www.ruv.de/rechtsschutzversicherung/immobilienrechtsschutz',{aliases:['Wohnungsrechtsschutz','Mietrecht'],docs:[D('Rechtsschutzbedingungen',DOCS.classic),D('comfort',DOCS.comfort)]}),

  P('hund-op','Hunde-OP-Versicherung','Komposit','Tier','Operationskostenversicherung der Vereinigte Tierversicherung Gesellschaft a.G., angeboten über R+V.','https://www.ruv.de/tierversicherung/hundeversicherung/hunde-op-versicherung',{featured:true,aliases:['Hund','OPK'],tariffs:[T('Basis','','bis 1.000 EUR je OP; Nachsorge 14 Tage; Geltung Europa'),T('Premium','','keine Höchstentschädigung je OP; Nachsorge 1 Monat; weltweit'),T('Exzellent','','keine Höchstentschädigung je OP; weitergehender Schutz u. a. bei angeborenen Fehlentwicklungen; weltweit')],highlights:['Aufnahme laut Produktseite bis Alter 8 Jahre; freie Tierarzt-/Klinikwahl.','Unfallbedingte OP: 1 Woche Wartezeit in Basis/Premium, keine im Exzellent; sonst i. d. R. 28 Tage.','Nach einem Jahr Vertragslaufzeit täglich kündbar laut Produktseite.'],docs:[D('AVB OPK Hund – erweitert',DOCS.hundOp)]}),
  P('pferd-op','Pferde-OP-Versicherung','Komposit','Tier','Operationskostenversicherung für Pferde in drei Leistungsstufen.','https://www.ruv.de/tierversicherung/pferdeversicherung/pferde-op-versicherung',{aliases:['Pferd','Pferde OP'],tariffs:[T('Basis','','bis 1.500 EUR je nach OP; Geltung Europa'),T('Premium','','Kolik-OP unbegrenzt, sonst bis 4.000 EUR; Europa'),T('Exzellent','','versicherte OP unbegrenzt; weltweiter Geltungsbereich')],highlights:['Höchstaufnahmealter laut Produktseite 15 Jahre.','Wartezeit Kolik-OP: 5 Tage in allen Varianten; unfallbedingte OP im Exzellent ohne Wartezeit.'],docs:[D('AVB OPK Pferd',DOCS.pferdOp)]}),
  P('hund-haft','Hundehalterhaftpflicht','Komposit','Tier','Spezielle Tierhalterhaftpflicht für Hunde mit den PrivatPolice-Leistungsstufen.','https://www.ruv.de/tierversicherung/hundeversicherung/hundehaftpflichtversicherung',{aliases:['Hundehaftpflicht','Hund'],tariffs:[T('classic'),T('comfort'),T('premium')],docs:CP}),
  P('pferd-haft','Pferdehalterhaftpflicht','Komposit','Tier','Spezielle Tierhalterhaftpflicht für Pferde mit den PrivatPolice-Leistungsstufen.','https://www.ruv.de/tierversicherung/pferdeversicherung/pferdehaftpflichtversicherung',{aliases:['Pferdehaftpflicht','Pferd'],tariffs:[T('classic'),T('comfort'),T('premium')],docs:CP}),
  P('pferd-leben','Tierlebensversicherung für Pferde','Komposit','Tier','Versicherung des Pferdewerts für definierte Risiken wie Tod/Nottötung; je Tarif kann auch Unbrauchbarkeit einbezogen sein.','https://www.ruv.de/tierversicherung/pferdeversicherung/tierlebensversicherung',{aliases:['Pferdeleben','Pferdewert'],docs:[D('Tierleben Pferde – Bedingungszentrale',DOCS.avb)]}),

  P('unfall','Risiko-Unfallversicherung','Komposit','Unfall','Private 24/7-Unfallabsicherung mit Kapital-/Rentenleistungen und optionalen Leistungspaketen.','https://www.ruv.de/unfallversicherung/risiko-unfallversicherung',{featured:true,aliases:['Unfall','Risiko UnfallPolice'],addons:['RisikoPlus','PremiumPlus','HilfePlus','KinderPlus'],highlights:['RisikoPlus: 50 % mehr Invaliditätsleistung bei Freizeitunfall ab 20 % Invaliditätsgrad.','PremiumPlus u. a. kosmetische OP bis 50.000 EUR, Kurkostenbeihilfe bis 25.000 EUR, Umbau Wohnung/Kfz bis 20.000 EUR.','HilfePlus: Hilfs-/Pflegeleistungen, Reha-Manager und bis zu 20.000 EUR für weitere Reha-Maßnahmen.'],docs:[D('R+V-Unfallversicherung – Verbraucherinfo/AVB',DOCS.unfall)]}),
  P('unfall-kapital','Unfallversicherung mit Beitragsrückgewähr / Kapital-UnfallPolice','Komposit','Unfall','Kombiniert privaten Unfallschutz mit einem Sparanteil und garantierter Kapitalleistung.','https://www.ruv.de/unfallversicherung/kapital-unfallversicherung-beitragsrueckgewaehr',{aliases:['Kapital Unfall','Beitragsrückgewähr'],addons:['KinderPlus'],highlights:['Mindestens 75 % des Nettobeitrags fließen laut Produktseite in den Sparanteil.','Kapitalleistung ab 1 % Invalidität; Unfallrente ab 50 % Invalidität.'],docs:[D('Kapital-UnfallPolice – Verbraucherinfo/AVB',DOCS.kapitalUnfall)]}),
  P('unfall-kind','Kinderunfallversicherung','Komposit','Unfall','Private Unfallabsicherung speziell für Kinder mit auf Kinder zugeschnittenen Leistungen.','https://www.ruv.de/unfallversicherung/kinderunfallversicherung',{aliases:['Kinderunfall','Kind'],addons:['KinderPlus'],docs:[D('R+V-Unfallversicherung – Bedingungen',DOCS.unfall)]}),
  P('unfall-bau','Risiko-Unfallversicherung für Bauherren und Bauhelfer','Komposit','Unfall','Unfallschutz für private Bauherren und Bauhelfer rund um das Bauvorhaben.','https://www.ruv.de/unfallversicherung/bauherren-bauhelfer',{aliases:['Bauhelfer','Bauherren Unfall'],docs:[D('R+V-Unfallversicherung – Bedingungen',DOCS.unfall)]}),

  P('pkv','Private Krankenversicherung – GesundheitsKonzept AGIL','Kranken','Vollversicherung','Private Krankenvollversicherung mit drei Tarifstufen und je vier Selbstbehaltsstufen.','https://www.ruv.de/private-krankenversicherung',{featured:true,aliases:['PKV','AGIL','Vollversicherung'],tariffs:[T('AGIL classic pro','','Einstieg; Leistungen in großen Teilen über GKV-Niveau.'),T('AGIL comfort','','u. a. Zweibettzimmer/privatärztlich stationär sowie Heilpraktiker-, Ergo- und Logopädie-Leistungen.'),T('AGIL premium','','u. a. Einbettzimmer, Leistungen über GOÄ/GOZ-Höchstsätze und höherer Zahnleistungsumfang.')],addons:['Selbstbehalt 0 EUR','Selbstbehalt 480 EUR','Selbstbehalt 960 EUR','Selbstbehalt 1.920 EUR','Beitragsentlastung im Alter','Krankentagegeld','Krankenhaustagegeld','Pflegemonatsgeld'],highlights:['Höherwertiger Tarifwechsel nach 5., 10. und 15. Versicherungsjahr (unter den auf der Produktseite genannten Altersvoraussetzungen) ohne erneute Gesundheitsprüfung.','Leistungsfreiheit kann Anspruch auf Beitragsrückerstattung auslösen; separat abgerechnete Vorsorge/Impfungen beeinträchtigen sie laut Produktseite nicht.','Private Pflegepflichtversicherung muss zusätzlich bestehen.'],docs:KV}),
  P('pkv-beamte','Private Krankenversicherung für Beamte – BeihilfeKonzept','Kranken','Vollversicherung · Beamte','Ergänzt die Beihilfe mit drei Leistungsstufen für Beamte und beihilfeberechtigte Personen.','https://www.ruv.de/private-krankenversicherung/private-krankenversicherung-beamte',{featured:true,aliases:['Beihilfe','Beamte','PKV Beamte'],tariffs:[T('Beihilfe classic'),T('Beihilfe comfort'),T('Beihilfe premium','','u. a. Einbettzimmer und Erstattung von Arzthonoraren auch über GOÄ-Höchstsatz hinaus je Tarifbedingungen')],highlights:['Produktseite nennt u. a. Vorsorge/Impfungen, mögliche Beitragsrückerstattung, Heilpraktikerleistungen, Zahnleistungen und offenen Hilfsmittelkatalog.'],docs:KV}),
  P('gkv','R+V BKK (gesetzliche Krankenversicherung)','Kranken','GKV · Partnerangebot','Gesetzliche Krankenkasse, auf der R+V-Seite als Krankenversicherungsangebot verlinkt; rechtlich keine private R+V Krankenversicherung.','https://www.ruv-bkk.de',{aliases:['BKK','GKV','gesetzliche'],highlights:['Bewusst separat markiert: Träger/Produktwelt ist R+V BKK, nicht die R+V Krankenversicherung AG.']}),
  P('reise-kv','Auslandsreise-Krankenversicherung','Kranken','Krankenzusatz','Auslandsschutz für medizinisch notwendige Behandlungen und Rücktransport bei Reisen.','https://www.ruv.de/reiseversicherung/reisekrankenversicherung',{featured:true,aliases:['Reisekranken','Auslandskranken','Urlaub'],highlights:['Schutz laut Produktseite jeweils für die ersten 45 Tage einer Auslandsreise.','Verlängerung ab Tag 46 bis zu 730 Tage möglich; ambulante Behandlung und verordnete Arzneimittel 100 % im beschriebenen Tarif.'],docs:KV}),
  P('zahn','Zahnzusatzversicherung','Kranken','Krankenzusatz','Drei Zahnersatz-Tarife ohne Wartezeit und laut Produktseite ohne Gesundheitsfragen.','https://www.ruv.de/krankenzusatzversicherung/zahnzusatzversicherung',{featured:true,aliases:['Zahn','Zahnersatz','Implantat'],tariffs:[T('Zahn classic','Z3U','Regelversorgung: 100 % GKV-Zuschuss, maximal verbleibender Eigenanteil.'),T('Zahn comfort','Z2U','Höherwertiger Zahnersatz 70 % unter Anrechnung GKV; KFO bis zu tariflichen Grenzen.'),T('Zahn premium','Z1U','Höherwertiger Zahnersatz 90 % unter Anrechnung GKV; höhere KFO-Grenzen.')],addons:['ZahnVorsorge'],highlights:['Comfort/premium Zahnstaffel: 1. Jahr 1.000 EUR, 2. Jahr 2.000 EUR, 3. Jahr 3.000 EUR, 4. Jahr 4.000 EUR Leistungsgrenze für Zahnersatz (außer Unfall).','Alterungsrückstellungen enthalten; laut Produktseite kein altersbedingter Beitragsanstieg.'],docs:KV}),
  P('klinik','Krankenhauszusatzversicherung – Tarife Klinik','Kranken','Krankenzusatz','Stationärer Zusatzschutz mit freier Arzt-/Krankenhauswahl und Wahlleistungen je Tarif.','https://www.ruv.de/krankenzusatzversicherung/krankenhauszusatzversicherung',{featured:true,aliases:['Klinik','Chefarzt','Einbettzimmer','Zweibettzimmer'],tariffs:[T('Klinik classic','K3U','Leistung bei Unfall; Zweibettzimmer; Arzthonorar bis GOÄ-Höchstsatz.'),T('Klinik comfort','K2U','Krankheit/Unfall/Schwangerschaft; Zweibettzimmer; bis GOÄ-Höchstsatz.'),T('Klinik premium','K1U','Krankheit/Unfall/Schwangerschaft; Ein- oder Zweibettzimmer; Erstattung auch über GOÄ-Höchstsatz möglich.')],highlights:['Versicherungsschutz laut Produktseite sofort ab Versicherungsbeginn.','Ambulante OP zur Vermeidung stationären Aufenthalts und stationäre Psychotherapie sind beschrieben.'],docs:KV}),
  P('ktg','Krankentagegeldversicherung','Kranken','Krankenzusatz','Sichert das Nettoeinkommen bei vorübergehender vollständiger Arbeitsunfähigkeit nach vereinbarter Karenzzeit ab.','https://www.ruv.de/krankenzusatzversicherung/krankentagegeldversicherung',{aliases:['KT','Krankentagegeld','Verdienstausfall'],highlights:['Maximal absicherbar ist das Nettoeinkommen unter Anrechnung anderer Ansprüche.','Für Selbstständige nennt die Produktseite Karenzzeiten ab zwei Wochen; Leistung auch an Sonn-/Feiertagen ohne feste zeitliche Begrenzung der vorübergehenden AU.','Entbindungspauschale: 12-faches vereinbartes Krankentagegeld.'],docs:KV}),
  P('kht','Krankenhaustagegeldversicherung','Kranken','Krankenzusatz','Zahlt den vereinbarten Betrag für jeden Tag medizinisch notwendigen stationären Aufenthalts zur freien Verfügung.','https://www.ruv.de/krankenzusatzversicherung/krankenhaustagegeld',{aliases:['KHT','Krankenhaus Tagegeld'],highlights:['Aufnahme- und Entlassungstag zählen mit; Schutz auch bei medizinisch notwendiger stationärer Behandlung im Ausland.'],docs:KV}),
  P('agu','Kostenerstattung ambulant','Kranken','Krankenzusatz','Ergänzt die GKV-Kostenerstattung, sodass gesetzlich Versicherte ambulant wie Privatpatienten abrechnen können.','https://www.ruv.de/krankenzusatzversicherung/ambulante-zusatzversicherung',{aliases:['AGU','Kostenerstattung','ambulant'],tariffs:[T('Kostenerstattung ambulant','AGU','Nach GKV-Vorleistung 80 % Restkosten; über 1.000 EUR erstattungsfähiger Restkosten im Kalenderjahr 100 %; ohne GKV-Vorleistung 40 % (tarifliche Grenzen beachten).')],highlights:['Zahnersatz und Kieferorthopädie sind nicht enthalten.','Allgemeine Wartezeit 3 Monate; besondere Wartezeit 8 Monate für Entbindung, Psychotherapie und Zahnbehandlung laut Produktseite.'],docs:KV}),
  P('naturmedizin','NaturMedizin','Kranken','Krankenzusatz','Zusatzschutz für definierte Naturheilverfahren bei Ärzten und Heilpraktikern.','https://www.ruv.de/krankenzusatzversicherung/zusatzversicherung-heilpraktiker',{aliases:['Heilpraktiker','Naturheilverfahren','N1U'],tariffs:[T('NaturMedizin','N1U','80 % erstattungsfähige Kosten; max. 2.400 EUR in zwei Kalenderjahren; in den ersten zwei Kalenderjahren ab Beginn max. 400 EUR.')],highlights:['Erstattungsfähige Methoden orientieren sich laut Produktseite am Hufelandverzeichnis.'],docs:KV}),
  P('blickcheck','Blick + Check','Kranken','Krankenzusatz','Kombiniert Zuschüsse für Sehhilfen/Augenlaser und ambulante Vorsorgeuntersuchungen.','https://www.ruv.de/krankenzusatzversicherung/brillenversicherung',{aliases:['Brille','Sehhilfe','Vorsorge','Augenlaser'],tariffs:[T('classic','BC3U','Je bis 100 EUR innerhalb von 2 Kalenderjahren für Sehhilfen/Augenlaser und Vorsorge.'),T('comfort','BC2U','Je bis 200 EUR innerhalb von 2 Kalenderjahren.'),T('premium','BC1U','Je bis 400 EUR innerhalb von 2 Kalenderjahren.')],highlights:['Laut Produktseite ohne Wartezeit, sofortiger Schutz ab Versicherungsbeginn.'],docs:KV}),
  P('plus-kombi','Kombitarif Zahnersatz + Sehhilfen + Vorsorge','Kranken','Krankenzusatz','Bündelt Zahn-, Sehhilfen- und Vorsorgeleistungen in Kombitarifen.','https://www.ruv.de/krankenzusatzversicherung/kombitarif-vorsorge',{aliases:['plus','Kombi Gesundheit','Zahn Blick Check'],highlights:['Produktseite nennt Beitragsvorteil bis zu 21 % gegenüber entsprechenden Einzeltarifen; nicht dauerhaft garantiert.','Sofortiger Schutz ohne Wartezeit laut Produktseite.'],docs:KV}),
  P('mitglieder-kv','Krankenzusatzversicherung für Mitglieder','Kranken','Krankenzusatz','Vergünstigte Tarifkombinationen für Mitglieder von Genossenschaften bzw. R+V BKK-Mitglieder.','https://www.ruv.de/krankenzusatzversicherung/mitglieder',{aliases:['Mitglieder','Genossenschaft'],docs:KV}),
  P('pflege-pflicht','Private Pflegepflichtversicherung','Kranken','Pflege','Gesetzlich vorgeschriebene Pflegepflichtversicherung für privat Krankenversicherte.','https://www.ruv.de/pflegeversicherung/private-pflegepflichtversicherung',{aliases:['PPV','Pflegepflicht'],docs:KV}),
  P('pflege-monat','Pflegemonatsgeld / R+V-PflegeVorsorge','Kranken','Pflege','Ergänzt die gesetzliche Pflegeabsicherung mit frei verfügbarem Monatsgeld und Assistance.','https://www.ruv.de/pflegeversicherung/pflege-zusatzversicherung/pflegemonatsgeldversicherung',{featured:true,aliases:['PflegeVorsorge','Pflegemonatsgeld'],tariffs:[T('classic','PM3','PG 5/4: 100 %; PG3 ambulant 70 %, stationär 100 %; PG1/2 keine Leistung.'),T('comfort','PM2','PG5/4 100 %; PG3 70/100 %; PG2 30/100 %; PG1 10 %.'),T('premium','PM1','PG2–5 100 % ambulant/stationär; PG1 10 %.')],addons:['PflegeVorsorge cash (PE)','Dynamik'],highlights:['Dynamik: bis Alter 70 alle drei Jahre +10 % ohne erneute Gesundheitsprüfung laut Produktseite.','Zu bestimmten Anlässen bis Alter 70 bis zu drei Verbesserungen/Erhöhungen ohne erneute Gesundheitsprüfung möglich (tarifliche Voraussetzungen beachten).','Familienleistung: zeitweise doppeltes Monatsgeld für pflegebedürftige Eltern bis Volljährigkeit des jüngsten Kindes; Beitragspause nach Geburt bis 2 Jahre laut Produktseite.'],docs:KV}),
  P('pflege-tag','R+V-Pflege FörderBahr','Kranken','Pflege','Staatlich gefördertes Pflegetagegeld ohne Gesundheitsfragen als ergänzende Pflegeabsicherung.','https://www.ruv.de/pflegeversicherung/pflege-zusatzversicherung/pflege-bahr',{aliases:['Pflegetagegeld','Pflege-Bahr','PflegeBahr','FörderBahr','PKB','staatlich geförderte Pflege'],tariffs:[T('Pflege FörderBahr','PKB','Leistung nach Pflegegrad; in Pflegegrad 5 mindestens 20 EUR täglich bzw. 600 EUR monatlich bei den Fördervoraussetzungen.')],highlights:['Staatlicher Zuschuss: 5 EUR monatlich bzw. 60 EUR im Jahr bei erfüllten Fördervoraussetzungen.','Keine Gesundheitsfragen sowie keine Risikozuschläge oder krankheitsbezogenen Leistungsausschlüsse laut Produktseite.','Leistungsstaffel laut Produktdarstellung: Pflegegrad 1/2/3/4/5 = 10/30/70/100/100 % des vereinbarten Tagegelds.','Regelwartezeit 5 Jahre; bei unfallbedingter Pflegebedürftigkeit entfällt sie nach Produktdarstellung.'],docs:[D('Pflege FörderBahr – R+V Bedingungszentrale',DOCS.avb)]}),

  P('risikoleben','Risikolebensversicherung','Leben','Hinterbliebenenschutz','Zahlt die vereinbarte Versicherungssumme im versicherten Todesfall; drei Leistungsstufen.','https://www.ruv.de/risikolebensversicherung',{featured:true,aliases:['Risikoleben','RLV','Todesfall'],tariffs:[T('classic','','Basis-Todesfallschutz mit Nachversicherungsgarantie nach AVB.'),T('comfort','','zusätzlich u. a. Verlängerungsoption bis 15 Jahre sowie Bau- und Kinder-Bonus.'),T('premium','','comfort-Leistungen plus Pflege-Bonus: 10 % der aktuellen Versicherungssumme, max. 15.000 EUR, bei den genannten Voraussetzungen.')],highlights:['Comfort/premium: Verlängerung einmalig um bis zu 15 Jahre ohne neue Risikoprüfung, bis 3 Jahre vor Vertragsende.','Kinder-Bonus und Bau-Bonus: jeweils bis 25.000 EUR zusätzlich bei den beschriebenen 6-Monats-Ereignisfenstern.'],docs:[D('AVB R+V-Risikoversicherung 1E37 – Stand 01.07.2026',DOCS.risiko)]}),
  P('sterbegeld','Sterbegeldversicherung','Leben','Hinterbliebenenschutz','Lebensversicherung zur Finanzierung von Bestattungskosten mit vereinbartem Sterbegeld.','https://www.ruv.de/sterbegeldversicherung',{aliases:['Sterbegeld','Bestattung'],highlights:['Volle Leistung nach 18 Monaten; bei Unfalltod bereits in der Wartezeit, sofern tarifliche Voraussetzungen erfüllt.','Bei anderem Tod in der Wartezeit werden laut Produktseite die geleisteten Beiträge zurückerstattet.','Beitragszahldauer abhängig vom Eintrittsalter: mindestens 5, maximal 25 Jahre.'],docs:LV}),
  P('vermoegen-uebertrag','Vermögensübertragung','Leben','Hinterbliebenenschutz','Lösungen zur strukturierten Vermögensübertragung mit Lebensversicherungsbausteinen.','https://www.ruv.de/vermoegensuebertragung',{aliases:['Erben','Schenken','Vermögen'],docs:LV}),
  P('bu','Berufsunfähigkeitsversicherung','Leben','Einkommensschutz','Monatliche BU-Rente bei bedingungsgemäßer Berufsunfähigkeit; drei aktuelle Produktvarianten.','https://www.ruv.de/berufsunfaehigkeitsversicherung',{featured:true,aliases:['BU','SBU','Berufsunfähigkeit','AU Klausel'],tariffs:[T('classic','BV29','BU-Rente nach 18 Monaten andauernder BU; keine AU-Option.'),T('comfort','BV30','rückwirkende Leistung ab Beginn der BU bei Erfüllung der Voraussetzungen; AU-Option möglich.'),T('premium','BV31','höherwertiger Leistungsumfang; rückwirkende Leistung ab Beginn; AU-Option möglich.')],addons:['AU-Option (nicht classic)','Beitragsdynamik','Leistungsdynamik','Fondslösung / steuerfreie Ablaufleistung'],highlights:['AVB-Stand laut Produktseite für BV29/BV30/BV31: 01.04.2026.','Volle Rente ab 50 % BU; Prognosezeitraum 6 Monate; Verzicht auf abstrakte Verweisung.','AU-Option: Leistung bei Krankschreibung bis zu 36 Monate laut Produktseite.'],docs:LV}),
  P('du','Dienstunfähigkeitsversicherung','Leben','Einkommensschutz','BU-Schutz für Beamte mit echter vollständiger sowie spezieller DU-Klausel für definierte Beamtengruppen.','https://www.ruv.de/berufsunfaehigkeitsversicherung/dienstunfaehigkeitsversicherung',{aliases:['DU','Beamte','Dienstunfähigkeit'],tariffs:[T('classic','BV29'),T('comfort','BV30'),T('premium','BV31')],highlights:['AVB-Stand laut R+V-Produktseite: 01.04.2026.','Bei bedingungsgemäßer DU nennt R+V Entlassungsbescheid/Versetzungsverfügung und amtsärztliches Gutachten als zentrale Nachweise; besondere Regeln stehen in den AVB.'],docs:LV}),
  P('gf','Grundfähigkeitsversicherung','Leben','Einkommensschutz','Zahlt eine vereinbarte Monatsrente bei bedingungsgemäßem Verlust bzw. Beeinträchtigung einer versicherten Grundfähigkeit.','https://www.ruv.de/grundfaehigkeitsversicherung',{aliases:['GF','Grundfähigkeit','Grundfähigkeiten'],tariffs:[T('comfort','','R+V-Seite stellt die Grundfähigkeitsabsicherung als comfort-Produkt heraus; maßgeblich ist der konkrete Tarif in den AVB.')],highlights:['Leistung bereits bei Verlust einer einzigen versicherten Grundfähigkeit.','Prognosezeitraum laut Produktseite 6 Monate; Nachversicherungsgarantie zu bestimmten Anlässen.','Versichert sind körperliche Fähigkeiten und Sinne wie Sehen, Hören, Sprechen, Tasten sowie Riechen/Schmecken nach Bedingungen.'],docs:LV}),
  P('restschuld','RatenschutzPolice / Restschuldversicherung','Leben','Einkommensschutz · Kredit','Absicherung einer Finanzierung gegen vereinbarte Ausfallrisiken wie Arbeitsunfähigkeit, Arbeitslosigkeit, Kurzarbeit, Scheidung oder Tod.','https://www.ruv.de/restschuldversicherung',{aliases:['RSV','Kredit','Restschuld','Ratenschutz','RatenschutzPolice','Kreditschutz','Restkreditversicherung'],highlights:['Die Produktseite nennt Finanzierungen bis 100.000 EUR und eine an die Kreditlaufzeit gekoppelte Versicherungsdauer von maximal 10 Jahren.','Für Arbeitslosigkeit, Kurzarbeit und Scheidung nennt R+V eine Wartezeit von 3 Monaten; für den Abschluss werden laut Produktdarstellung keine Gesundheitsfragen gestellt.','Je nach versichertem Risiko: monatliche Leistung bis 2.500 EUR bei Arbeitslosigkeit/Kurzarbeit oder Arbeitsunfähigkeit, Scheidungsleistung bis 15.000 EUR; im Todesfall 110 % der aktuellen versicherten Summe.'],docs:[D('RatenschutzPolice – R+V Bedingungszentrale',DOCS.avb)]}),
  P('cashprotect','CashProtect','Leben','Einkommensschutz · Kredit','R+V-Lösung zum Schutz laufender finanzieller Verpflichtungen bei vereinbarten Ausfallrisiken.','https://www.ruv.de/cashprotect',{aliases:['Cash Protect','Ratenschutz'],docs:LV}),

  P('anspar','AnsparKombi Safe+Smart','Leben','Private Rente & Vorsorge','Private Rentenversicherung mit sicherem Kapital und Chancen-Kapital; flexible Ein-/Auszahlungen.','https://www.ruv.de/geldanlage/ansparkombi',{featured:true,aliases:['Safe Smart','AnsparKombi','VorsorgeSparen'],highlights:['Mindestens 50 % der Sparrate fließen in das sichere Kapital; Chancen-Kapital wird indexorientiert angelegt.','Monatliche Sparrate laut Produktseite 25–2.500 EUR; Zuzahlungen 500–20.000 EUR/Jahr.','Teilauszahlungen: min. 1.000 EUR, danach mindestens 2.500 EUR Gesamtkapital; Frist ein Monat zum nächsten Monatsersten.'],docs:LV}),
  P('anlage','AnlageKombi Safe+Smart','Leben','Private Rente & Vorsorge','Einmalanlage-orientierte Safe+Smart-Lösung mit Kombination aus Sicherheit und Kapitalmarktchancen.','https://www.ruv.de/geldanlage/anlagekombi',{aliases:['Safe Smart','AnlageKombi','Einmalanlage'],docs:LV}),
  P('fondsrente','Fondsgebundene Rentenversicherung / R+V-VorsorgeKonzept','Leben','Private Rente & Vorsorge','Fondsgebundene Rentenversicherung mit breiter Fonds-/Strategieauswahl und flexibler Auszahlung.','https://www.ruv.de/altersvorsorge/private-rentenversicherung/rv-vorsorge-konzept',{aliases:['Fondsrente','VorsorgeKonzept','Union Investment'],highlights:['Sparen laut Produktseite ab 25 EUR/Monat oder Einmalbetrag.','Anlagestrategie/Fonds bis zu 12-mal im Jahr kostenfrei anpassbar; Auszahlung als Kapital, Rente oder Kombination.'],docs:LV}),
  P('duoinvest','InvestmentKonzept Duo Invest','Leben','Private Rente & Vorsorge','Verbindet aktiv gemanagte Union-Investment-Strategien mit einer R+V-Rentenversicherung.','https://www.ruv.de/altersvorsorge/private-rentenversicherung/duoinvest',{aliases:['Duo Invest','Union Investment'],highlights:['Flexible Monats-/Einmalzahlung; Todesfallschutz durch Beitragsrückgewähr laut Produktseite.'],docs:LV}),
  P('indexinvest','PrivatRente IndexInvest','Leben','Private Rente & Vorsorge','Indexorientierte Privatrente mit Beitragsgarantie-Mechanik und jährlicher Wahl der Anlageform.','https://www.ruv.de/altersvorsorge/private-rentenversicherung/privat-rente-indexinvest',{aliases:['IndexInvest','Indexrente','SOMAS'],highlights:['Produktseite: Policenwert kann nicht fallen; jährliche Wahl zwischen sicherer Verzinsung und zwei Indexpartizipationsvarianten.','Vor Rentenbeginn sind kostenfreie Entnahmen nach den vertraglichen Regeln möglich.'],docs:LV}),
  P('ruerup-fonds','Fondsgebundene Rürup-Rente','Leben','Basisrente','Fondsgebundene Basisrente mit steuerlicher Förderung und lebenslanger Rentenzahlung.','https://www.ruv.de/altersvorsorge/private-rentenversicherung/ruerup-rente',{aliases:['Rürup','Basisrente','Fonds'],highlights:['Beiträge zu Basisrenten sind im gesetzlichen Höchstbetragsrahmen zu 100 % als Sonderausgaben absetzbar.','Rentenbeginn laut Produktseite ab vollendetem 62. Lebensjahr bis maximal zum rechnungsmäßigen 70. Lebensjahr verschiebbar.'],docs:LV}),
  P('basis-safe','BasisRente Safe+Smart','Leben','Basisrente','Basisrente mit sicherem Kapital und Kapitalmarktchancen, lebenslanger garantierter Rentenzahlung.','https://www.ruv.de/altersvorsorge/private-rentenversicherung/ruerup-rente/safe-und-smart',{aliases:['Rürup Safe Smart','Basisrente'],highlights:['Beiträge im gesetzlichen Rahmen zu 100 % als Sonderausgaben absetzbar; flexible Anpassung der Anlagestrategie laut Produktseite.'],docs:LV}),
  P('sofort','SofortRente','Leben','Private Rente & Vorsorge','Einmalbeitrag gegen sofort beginnende lebenslange garantierte Rentenzahlung.','https://www.ruv.de/altersvorsorge/private-rentenversicherung/sofortrente',{aliases:['Sofortrente','Einmalbeitrag'],addons:['Beitragsrückgewähr','Garantiezeit','Hinterbliebenen-Zusatzversicherung'],highlights:['Keine Gesundheitsprüfung; Besteuerung der Rentenleistung mit Ertragsanteil.','Hinterbliebenenschutz wahlweise über Beitragsrückgewähr, Garantiezeit oder Hinterbliebenen-Zusatzversicherung gestaltbar.'],docs:LV}),
  P('bav','Direktversicherung durch Entgeltumwandlung','Leben','Betriebliche Altersvorsorge','Betriebliche Altersvorsorge über Direktversicherung mit Beiträgen aus dem Arbeitsentgelt.','https://www.ruv.de/altersvorsorge/betriebliche-altersvorsorge/direktversicherung',{aliases:['bAV','Direktversicherung','Entgeltumwandlung'],docs:LV}),
  P('lebensarbeitszeit','Lebensarbeitszeitkonto','Leben','Vorsorge · Arbeitszeit','Wertguthaben-Lösung für Beschäftigte und Arbeitgeber, um Entgeltbestandteile oder Zeitwerte für spätere bezahlte Freistellungen anzusparen.','https://www.ruv.de/altersvorsorge/lebensarbeitszeitkonto',{aliases:['Zeitwertkonto','Wertguthaben','Lebensarbeitszeit','Sabbatical','Freistellung'],highlights:['Vorsorgelösung rund um ein Wertguthaben; keine klassische private Einzelversicherung.','Typische Beratungsanlässe sind längerfristige Freistellungen, Sabbatical oder ein früherer Übergang aus dem Erwerbsleben.']}),
  P('schueler-bu','Berufsunfähigkeitsversicherung für Schüler','Leben','Kinder & Schüler','Früher BU-Einstieg für Schüler; Produktseite nennt Absicherung ab der 5. Klasse und ab 10 Jahren.','https://www.ruv.de/berufsunfaehigkeitsversicherung/schueler',{aliases:['Schüler BU','Kinder BU'],tariffs:[T('Start comfort','BVS','Beispielhafte Startphase; spätere Beiträge und Leistung nach AVB.')],docs:LV}),
  P('kind-rund','KinderRundumschutz','Leben','Kinder & Schüler','Flexibles Paket aus Kapitalbildung, Gesundheitsschutz und Unfallschutz für Kinder.','https://www.ruv.de/versicherung-fuer-kinder/kinderrundumschutz',{aliases:['Kinder','Rundumschutz'],addons:['AnsparKombi Safe+Smart','Kranken-/Pflege-Zusatzschutz','Kinderunfallversicherung'],docs:[D('R+V Bedingungszentrale',DOCS.avb)]}),
  P('kind-index','KinderVorsorge IndexInvest','Leben','Kinder & Schüler','Indexorientierte langfristige Vorsorgelösung für Kinder innerhalb der R+V-Kinder-Vorsorgewelt.','https://www.ruv.de/versicherung-fuer-kinder',{aliases:['KinderVorsorge','IndexInvest','Kindersparen'],docs:LV}),
  P('sparen-kind','Sparen für Kinder','Leben','Kinder & Schüler','Produktweg für langfristigen Kapitalaufbau: u. a. AnsparKombi Safe+Smart, AnlageKombi Safe+Smart und KinderVorsorge IndexInvest.','https://www.ruv.de/versicherung-fuer-kinder/sparen-fuer-kinder',{aliases:['Kindersparen','Kinder'],docs:LV})
];
