/*
 * RuVKompendium 9 – Evidence Layer
 * Geprüft 10.08.2026 anhand offizieller R+V-Bedingungswerke bzw. ausdrücklich
 * gekennzeichneter R+V-Produktseiten. Die Kurztexte sind redaktionelle
 * Verdichtungen der angegebenen Fundstellen, keine vollständige AVB-Wiedergabe.
 */
const EVIDENCE_META={edition:9,checked:'10.08.2026'};

const EVIDENCE={
  'kfz-auto':[
    {anchor:'tariff:premium',label:'Neupreisentschädigung premium',kind:'Bedingungswerk',source:'R+V Verbraucherinformation für Pkw',code:'AKB · Stand Juli 2026',location:'A.2.6 · S. 22',quote:'in der KfzPolice premium innerhalb von 30 Monaten',text:'Bei Totalschaden, Zerstörung oder Verlust kann in premium innerhalb von 30 Monaten nach Erstzulassung der Neupreis maßgeblich sein; die weiteren Voraussetzungen stehen in A.2.6.'},
    {anchor:'tariff:comfort',label:'Neupreisentschädigung comfort',kind:'Bedingungswerk',source:'R+V Verbraucherinformation für Pkw',code:'AKB · Stand Juli 2026',location:'A.2.6 · S. 22',text:'Für comfort nennt A.2.6 bei Totalschaden, Zerstörung oder Verlust eine Neupreisregelung innerhalb von 12 Monaten nach Erstzulassung; weitere Voraussetzungen sind zu beachten.'},
    {anchor:'addon:fahrerschutz',label:'Fahrerschutz',kind:'Bedingungswerk',source:'R+V Verbraucherinformation für Pkw',code:'AKB · Stand Juli 2026',location:'A.6.1–A.6.4 · S. 44–45',text:'Versichert ist der berechtigte Fahrer. Die Leistung für seinen Personenschaden erfolgt nach deutschem Haftpflichtrecht bis zur in A.6.4 genannten Höchstleistung.'},
    {anchor:'addon:gap differenzdeckung',label:'Differenzdeckung / GAP',kind:'Bedingungswerk',source:'R+V Verbraucherinformation für Pkw',code:'AKB · Stand Juli 2026',location:'A.7 · S. 46–47',text:'A.7 regelt die Differenzdeckung für Leasing- und kreditfinanzierte Pkw einschließlich versicherter Ereignisse, Leistungsberechnung und Ausschlüsse.'}
  ],

  'kfz-eauto':[
    {anchor:'highlight:0',label:'E-/Hybrid-Beitragsnachlass',kind:'R+V Produktseite',source:'Kfz-Versicherung für E-Autos',code:'Produktdarstellung · geprüft 08.08.2026',location:'Vorteile E-Auto-Versicherung',text:'R+V nennt für Elektro- und Hybrid-Pkw einen Beitragsnachlass von 3 %. Maßgeblich für die konkrete Prämie bleibt die individuelle Tarifierung.'},
    {anchor:'highlight:1',label:'Akku mitversichert',kind:'R+V Produktseite / AKB',source:'Kfz-Versicherung für E-Autos',code:'Produktdarstellung + AKB 07/2026',location:'Leistungen Akku / Kasko',text:'Der Fahrakku ist im Rahmen der vereinbarten Kaskodeckung gegen die tariflich beschriebenen versicherten Gefahren einbezogen. Verschleiß bzw. reine altersbedingte Kapazitätsminderung ist davon zu unterscheiden.'},
    {anchor:'highlight:2',label:'Akku-Neupreis premium',kind:'R+V Produktseite',source:'Kfz-Versicherung für E-Autos',code:'premium · geprüft 08.08.2026',location:'FAQ Akku',text:'Die aktuelle Produktseite beschreibt für premium bei einem versicherten Akkuschaden eine Neupreiserstattung bis 36 Monate nach Kauf des Akkus. Weitere Voraussetzungen ergeben sich aus der vereinbarten Kaskodeckung.'}
  ],

  'kfz-motorrad':[
    {anchor:'tariff:haftpflicht',label:'Motorrad-Haftpflicht',kind:'R+V Produktseite',source:'R+V-Motorradversicherung',code:'Produktübersicht · geprüft 08.08.2026',location:'Kfz-Haftpflicht',text:'Die Produktseite nennt 100 Mio. EUR pauschale Deckung für Personen-, Sach- und Vermögensschäden, begrenzt auf 15 Mio. EUR je geschädigter Person.'},
    {anchor:'highlight:0',label:'Tierbiss-Folgeschäden',kind:'R+V Produktseite',source:'R+V-Motorradversicherung',code:'Kaskoleistung · geprüft 08.08.2026',location:'Leistungen Kasko',text:'Für Folgeschäden nach Tierbiss/Marder nennt R+V auf der Motorrad-Produktseite eine Grenze bis 5.000 EUR; die konkrete Deckung setzt den vereinbarten Kaskoschutz voraus.'},
    {anchor:'highlight:1',label:'Zweitfahrzeug-Einstufung',kind:'R+V Produktseite',source:'R+V-Motorradversicherung',code:'SF-Regel · geprüft 08.08.2026',location:'Zweitfahrzeug / Schadenfreiheitsklasse',text:'Bei den auf der Produktseite beschriebenen Voraussetzungen kann ein als Zweitfahrzeug versichertes Motorrad bis zur Schadenfreiheitsklasse SF 3 eingestuft werden.'}
  ],

  'kfz-zweitwagen':[
    {anchor:'highlight:0',label:'SF-Einstufung Zweitwagen',kind:'R+V Produktseite',source:'R+V-Zweitwagenversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Zweitwagen bei gleicher/anderer Versicherung',text:'Eine nachgewiesene vorhandene Schadenfreiheitsklasse kann die Einstufung verbessern. R+V weist ausdrücklich darauf hin, dass das Erstfahrzeug dafür nicht zwingend bei R+V versichert sein muss.'},
    {anchor:'highlight:1',label:'Nicht gleiche SF wie Erstwagen',kind:'R+V Produktseite',source:'R+V-Zweitwagenversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Zweitwagen wie Erstwagen?',text:'Der Zweitwagen kann nicht einfach mit derselben SF-Klasse wie der Erstwagen versichert werden; dieselben Tarifmodelle können jedoch ausgewählt werden.'},
    {anchor:'highlight:2',label:'Weitere Fahrzeuge',kind:'R+V Produktseite',source:'R+V-Zweitwagenversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Drittwagen / mehrere Fahrzeuge',text:'Für Drittwagen und weitere Fahrzeuge beschreibt R+V dieselben Regeln wie für einen Zweitwagen.'}
  ],

  'kfz-roller':[
    {anchor:'eligibility:0',label:'Abgrenzung Versicherungskennzeichen',kind:'R+V Produktseite',source:'R+V-Moped- und Rollerversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Versicherungsbedingungen / Hinweis Fahrzeuggrenzen',text:'Modelle mit einem Hubraum über 50 ccm oder einer bauartbedingten Höchstgeschwindigkeit über 60 km/h können laut R+V nicht über die Moped-/Rollerversicherung versichert werden; R+V verweist dafür auf Motorrad- bzw. 125-ccm-Tarife.'},
    {anchor:'eligibility:1',label:'Versicherungsjahr Kennzeichen',kind:'R+V Produktseite',source:'R+V-Moped- und Rollerversicherung',code:'Versicherungskennzeichen · geprüft 08.08.2026',location:'Das Wichtigste',text:'Das Versicherungskennzeichen gilt jeweils vom 1. März bis zum letzten Tag im Februar des Folgejahres und muss jährlich erneuert werden.'},
    {anchor:'highlight:0',label:'Teilkasko Kleinkrafträder',kind:'R+V Produktseite / Leistungstabelle',source:'Versicherungskennzeichen für Moped, Roller und Co.',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen Teilkasko',text:'Als Teilkasko-Leistungen nennt R+V beispielhaft Diebstahl/Raub, Brand/Explosion, Sturm/Hagel/Blitz/Überschwemmung, Tierkollision, Tierbiss-Folgeschäden an Kabeln/Schläuchen/Leitungen bis 500 EUR und Glasbruch.'}
  ],

  'kfz-moped':[
    {anchor:'eligibility:0',label:'Fahrzeuggrenzen Moped-Tarif',kind:'R+V Produktseite',source:'R+V-Moped- und Rollerversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Hinweis Fahrzeuggrenzen',text:'Modelle mit über 50 ccm Hubraum oder bauartbedingter Höchstgeschwindigkeit über 60 km/h sind nach der Produktdarstellung nicht über diesen Versicherungskennzeichen-Tarif versicherbar.'},
    {anchor:'eligibility:1',label:'Kennzeichenjahr Moped',kind:'R+V Produktseite',source:'R+V-Moped- und Rollerversicherung',code:'Versicherungskennzeichen · geprüft 08.08.2026',location:'Das Wichtigste',text:'Das Versicherungskennzeichen gilt vom 1. März bis zum letzten Tag im Februar des Folgejahres und ist jährlich neu zu beantragen.'},
    {anchor:'highlight:0',label:'Teilkasko Moped',kind:'R+V Produktseite / Leistungstabelle',source:'Versicherungskennzeichen für Moped, Roller und Co.',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen Teilkasko',text:'Die R+V-Leistungsübersicht nennt u. a. Diebstahl/Raub, Brand/Explosion, Naturgefahren, Tierkollision, Tierbiss-Folgeschäden bis 500 EUR und Glasbruch als Beispiele der Teilkasko.'}
  ],

  'kfz-escooter':[
    {anchor:'eligibility:0',label:'Fahrer-/Abschlussalter E-Scooter',kind:'R+V Produktseite',source:'R+V-E-Scooter-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Fahrer / Minderjährige',text:'R+V weist aus, dass ein E-Scooter ab Alter 14 ohne Führerschein gefahren werden darf. Minderjährige können den Versicherungsvertrag nur mit Zustimmung der Eltern bzw. gesetzlichen Vertreter abschließen.'},
    {anchor:'eligibility:1',label:'Betriebserlaubnis E-Scooter',kind:'R+V Produktseite',source:'R+V-E-Scooter-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Teilkasko / Voraussetzung',text:'Voraussetzung für den Versicherungsschutz ist nach der Produktseite eine gültige Allgemeine Betriebserlaubnis (ABE) oder Einzelbetriebserlaubnis.'},
    {anchor:'eligibility:2',label:'Versicherungsjahr E-Scooter',kind:'R+V Produktseite',source:'R+V-E-Scooter-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Laufzeit',text:'Die E-Scooter-Versicherung läuft für ein Versicherungsjahr vom 1. März bis zum letzten Februartag und verlängert sich nicht automatisch; für das Folgejahr ist eine neue Versicherungsplakette erforderlich.'},
    {anchor:'highlight:0',label:'Teilkasko E-Scooter',kind:'R+V Produktseite',source:'R+V-E-Scooter-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Teilkasko / Leistungsbeispiel',text:'Die optionale Teilkasko schützt nach Produktdarstellung beispielsweise bei Diebstahl und Naturgefahren. Im gezeigten Diebstahlfall wird bis zum Wiederbeschaffungswert des E-Scooters geleistet.'}
  ],

  'kfz-ebike':[
    {anchor:'eligibility:0',label:'Versicherungspflicht E-Bike/S-Pedelec',kind:'R+V Produktseite',source:'R+V-E-Bike-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Fahrzeugtypen / Versicherungspflicht',text:'E-Bikes mit eigenständigem Motorantrieb und S-Pedelecs mit Unterstützung bis 45 km/h werden als versicherungspflichtige Kleinkrafträder mit Versicherungskennzeichen beschrieben.'},
    {anchor:'eligibility:1',label:'Pedelec bis 25 km/h',kind:'R+V Produktseite',source:'R+V-E-Bike-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Fahrzeugtypen / Versicherungspflicht',text:'Pedelecs mit Tretunterstützung nur bis 25 km/h gelten rechtlich als Fahrräder und benötigen laut R+V kein Versicherungskennzeichen.'},
    {anchor:'highlight:0',label:'Teilkasko E-Bike',kind:'R+V Produktseite',source:'R+V-E-Bike-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Was ist versichert?',text:'Die optionale Teilkasko nennt unter anderem Diebstahl/Teilediebstahl, Brand, Sturm, Hagel, Blitzschlag, Überschwemmung und Zusammenstoß mit Tieren.'},
    {anchor:'highlight:1',label:'Akku-Neupreis 24 Monate',kind:'R+V Produktseite',source:'R+V-E-Bike-Versicherung',code:'Teilkasko · geprüft 08.08.2026',location:'Leistungsbeispiel Akku',text:'Bei Akkus von Elektrofahrzeugen beschreibt R+V eine Neupreisleistung, wenn innerhalb von bis zu 24 Monaten nach Neukauf Totalschaden, Zerstörung oder Verlust durch ein versichertes Ereignis eintritt.'},
    {anchor:'highlight:2',label:'Personenschaden E-Bike',kind:'R+V Produktseite',source:'R+V-E-Bike-Versicherung',code:'Haftpflicht · geprüft 08.08.2026',location:'Leistungsbeispiel Personenschaden',text:'Für Personenschäden nennt die Produktseite eine Haftpflichtleistung bis 12 Mio. EUR je Geschädigtem.'}
  ],

  'kfz-wohnmobil':[
    {anchor:'highlight:0',label:'Geltungsbereich Wohnmobil',kind:'R+V Produktseite',source:'R+V-Wohnmobil-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Produktvorteile',text:'R+V beschreibt den Versicherungsschutz der Wohnmobil-Versicherung als gültig in Europa und den außereuropäischen Gebieten der EU.'},
    {anchor:'highlight:1',label:'Kasko-Extra Wohnmobil',kind:'R+V Produktseite',source:'R+V-Wohnmobil-Versicherung',code:'KEX · geprüft 08.08.2026',location:'Zusatzbaustein Kasko-Extra',text:'Kasko-Extra erweitert nach Produktdarstellung die Vollkaskodeckung in comfort/premium um bestimmte unvorhergesehene Brems-, Betriebs- und Bruchschäden.'},
    {anchor:'highlight:2',label:'Schloss-/Schlüsselkosten',kind:'R+V Produktseite',source:'R+V-Wohnmobil-Versicherung',code:'Teilkasko · geprüft 08.08.2026',location:'Wichtigste Teilkaskoleistungen',text:'Als zusätzliche Teilkaskoleistung nennt R+V die Erstattung von Kosten für den Austausch von Schlössern und zugehörigen Schlüsseln nach Diebstahl eines Schlüssels.'}
  ],

  'kfz-wohnwagen':[
    {anchor:'eligibility:0',label:'Zulassung Wohnwagen',kind:'R+V Produktseite',source:'R+V-Wohnwagenversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Vorteile / Dauercamper / Stilllegung',text:'Die R+V-Wohnwagenversicherung gilt grundsätzlich für zugelassene Wohnwagen. Für nicht zugelassene Dauercamper oder abgemeldete Fahrzeuge ist ein anderer bzw. ergänzender Versicherungsschutz erforderlich.'},
    {anchor:'highlight:0',label:'Zubehör Wohnwagen',kind:'R+V Produktseite',source:'R+V-Wohnwagenversicherung',code:'Teilkasko / Vollkasko · geprüft 08.08.2026',location:'FAQ Zubehör / Sat-Anlagen',text:'Fahrzeug- und Zubehörteile können beitragsfrei mitversichert sein, wenn sie unter Verschluss, fest eingebaut oder dauerhaft über Halterungen verbunden sind. Fest verbundene Sat-Anlagen werden als Beispiel genannt; der Gesamtneuwert ist zu berücksichtigen.'},
    {anchor:'highlight:1',label:'Kein automatischer Ruheschutz',kind:'R+V Produktseite',source:'R+V-Wohnwagenversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Stilllegung/Abmeldung',text:'R+V weist ausdrücklich darauf hin, dass für die Wohnwagenversicherung bei Stilllegung/Abmeldung kein automatischer Ruheversicherungsschutz besteht.'},
    {anchor:'highlight:2',label:'Hausrat im Wohnwagen',kind:'R+V Produktseite',source:'R+V-Wohnwagenversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Hausrat',text:'Der Hausrat im Wohnwagen ist nicht Bestandteil der Wohnwagen-Kfz-Versicherung. R+V verweist für Inventar auf die mögliche Außenversicherung der Hausratversicherung.'}
  ],

  'kfz-anhaenger':[
    {anchor:'eligibility:0',label:'Haftpflichtpflicht Anhänger',kind:'R+V Produktseite',source:'R+V-Anhänger-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ / Haftpflicht',text:'Für einen zugelassenen Anhänger, der auf öffentlichen Straßen genutzt wird, ist nach der Produktdarstellung eine eigene Haftpflichtversicherung erforderlich.'},
    {anchor:'eligibility:1',label:'Versicherbare Anhängertypen',kind:'R+V Produktseite',source:'R+V-Anhänger-Versicherung',code:'Privatweg · geprüft 08.08.2026',location:'FAQ versicherte Anhänger',text:'Im Privatweg nennt R+V Wohnwagenanhänger einschließlich klappbarer Wohnanhänger sowie Anhänger Privatverkehr zum Transport eigener Güter. Für Pferde- und Bootsanhänger verweist R+V auf individuelle Beratung.'},
    {anchor:'highlight:0',label:'Haftpflicht-Zusatzleistungen Anhänger',kind:'R+V Produktseite',source:'R+V-Anhänger-Versicherung',code:'Haftpflicht · geprüft 08.08.2026',location:'Übersicht wichtigste Leistungen',text:'Die Produktseite nennt 100 Mio. EUR Haftpflichtsumme, höchstens 12 Mio. EUR je geschädigte Person, sowie integrierte Mallorca-Police und Kfz-Umweltschadensversicherung.'}
  ],

  'mietkaution':[
    {anchor:'eligibility:0',label:'Young-Tarif Alter',kind:'R+V Produktseite',source:'R+V-MietkautionsBürgschaft',code:'Young-Tarif · geprüft 08.08.2026',location:'Young-Tarif',text:'Der Young-Tarif richtet sich an 18- bis 25-Jährige. Besteht das Mietverhältnis fort, bleibt die Bürgschaft nach Produktdarstellung auch über das 26. Lebensjahr hinaus bestehen.'},
    {anchor:'eligibility:1',label:'Young-Tarif Kautionshöhe',kind:'R+V Produktseite',source:'R+V-MietkautionsBürgschaft',code:'Young-Tarif · geprüft 08.08.2026',location:'Young-Tarif',text:'R+V nennt für den Young-Tarif Kautionssummen von 500 EUR bis 1.500 EUR.'},
    {anchor:'highlight:1',label:'Neu oder bestehend',kind:'R+V Produktseite',source:'R+V-MietkautionsBürgschaft',code:'Produktdarstellung · geprüft 08.08.2026',location:'Produktvorteile',text:'Die R+V-MietkautionsBürgschaft kann nach der aktuellen Produktdarstellung für neue wie auch für bereits bestehende private Mietverhältnisse genutzt werden.'}
  ],

  'sichervermieten':[
    {anchor:'highlight:0',label:'Mietrückstände',kind:'R+V Produktseite / Makler-Kundeninformation',source:'R+V-SicherVermieten',code:'PrivatPolice · geprüft 08.08.2026',location:'Sicherung der Mieteinnahmen',text:'R+V beschreibt die Übernahme versicherter Mietrückstände für bis zu drei Monate. Leistungsvoraussetzungen und Grenzen richten sich nach der vereinbarten SicherVermieten-Deckung.'},
    {anchor:'highlight:1',label:'Renovierungs-Leerstand',kind:'R+V Produktseite / Makler-Kundeninformation',source:'R+V-SicherVermieten',code:'PrivatPolice · geprüft 08.08.2026',location:'Schutz vor Leerstand',text:'Für die Renovierungszeit nach Auszug beschreibt R+V die Übernahme entgangener Mieteinnahmen für bis zu drei Monate, soweit die tariflichen Voraussetzungen erfüllt sind.'},
    {anchor:'highlight:2',label:'Sachschäden',kind:'R+V Produktseite',source:'R+V-SicherVermieten',code:'Produktdarstellung · geprüft 08.08.2026',location:'Kostenerstattung bei Sachschäden',text:'Bei versicherten Beschädigungen oder Entwendungen durch Mieter nennt R+V die Erstattung des Zeitwerts im vereinbarten Umfang.'}
  ],

  'geraeteschutz':[
    {anchor:'eligibility:0',label:'Gerätealter bei Abschluss',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Welche Geräte sind versichert?',text:'Abgesichert werden kann Equipment, dessen Alter bei Vertragsabschluss 36 Monate ab Neukaufdatum nicht überschreitet.'},
    {anchor:'eligibility:1',label:'Gerätealter im Schadenfall',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Welche Geräte sind versichert?',text:'Nach der Produktdarstellung darf das versicherte Gerät im Schadenfall nicht älter als 60 Monate ab Neukaufdatum sein.'},
    {anchor:'highlight:0',label:'Grundschutz GeräteSchutz',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'Die Produktdarstellung nennt unter anderem Fall/Sturz, Flüssigkeit/Feuchtigkeit, technische Schäden, Sabotage/Vandalismus, Brand/Blitz/Überspannung und Diebstahl als versicherbare Schadenursachen des Grundschutzes.'},
    {anchor:'highlight:1',label:'Versicherbare und ausgeschlossene Geräte',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Welche Geräte sind versichert?',text:'Versicherbar sind unter anderem Computer, Monitore, Konsolen, Peripherie und Streaming-Equipment. Handys, Smartphones, Tablets, Smartwatches, Ausstellungsgeräte und Reimporte werden als nicht versicherbar genannt.'},
    {anchor:'highlight:2',label:'Vertragslaufzeit GeräteSchutz',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Vertragslaufzeit',text:'Die Mindestvertragslaufzeit beträgt ein Jahr. Danach verlängert sich der Vertrag jeweils um ein Jahr; nach der Mindestlaufzeit beschreibt R+V eine monatliche Kündigungsmöglichkeit.'},
    {anchor:'addon:tech upgrade',label:'Tech-Upgrade',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Tech',text:'Bei einer versicherten Reparatur kann der Zusatzbaustein einen Zuschuss von 10 % des Gerätewerts für technisch fortgeschrittenere Teile vorsehen.'},
    {anchor:'addon:verschleiss',label:'Verschleiß',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Verschleiß',text:'Der Baustein Verschleiß nennt bis zu 150 EUR je Versicherungsfall und Versicherungsjahr für Verschleiß bzw. innere Betriebsschäden elektronischer Bauteile.'},
    {anchor:'addon:transport',label:'Transport',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Transport',text:'Der Transport-Baustein erweitert den Schutz um Schäden an versicherter Hardware während eines privaten Transports.'},
    {anchor:'addon:unsachgemasse handhabung',label:'Unsachgemäße Handhabung',kind:'R+V Produktseite',source:'R+V-Laptop-/Hardware-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Unsachgemäße Handhabung',text:'Der Baustein erweitert den Schutz um Schäden durch unsachgemäße Handhabung, beispielsweise falsche Bedienung.'}
  ],

  'laptop':[
    {anchor:'eligibility:0',label:'Gerätealter Abschluss',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Welche Geräte sind versichert?',text:'Laptops und weitere versicherbare Hardware dürfen bei Abschluss höchstens 36 Monate seit Neukauf alt sein.'},
    {anchor:'eligibility:1',label:'Gerätealter Schadenfall',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ',text:'Im Schadenfall darf das versicherte Equipment nach Produktdarstellung höchstens 60 Monate ab Neukaufdatum alt sein.'},
    {anchor:'eligibility:2',label:'Vertragslaufzeit Laptop-Versicherung',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Vertragslaufzeit',text:'Die Mindestvertragslaufzeit beträgt ein Jahr. Der Vertrag verlängert sich jeweils um ein weiteres Jahr; nach Ablauf der Mindestvertragslaufzeit beschreibt R+V eine monatliche Kündigungsmöglichkeit.'},
    {anchor:'highlight:0',label:'Grundgefahren Laptop/Hardware',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'Der Grundschutz nennt unter anderem Fall/Sturz, Flüssigkeit/Feuchtigkeit, technische Schäden, Sabotage/Vandalismus, grobe Fahrlässigkeit, Brand/Blitz/Explosion/Überspannung, Sturm/Frost und Überschwemmung.'},
    {anchor:'highlight:1',label:'Diebstahl und Raub',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen / Abhandenkommen',text:'Die Produktdarstellung nennt Diebstahl, Einbruchdiebstahl und Raub als versicherte Formen des Abhandenkommens.'},
    {anchor:'addon:verschleiss bis 150 eur je versicherungsfall und jahr',label:'Upgrade Verschleiß',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Verschleiß',text:'Der Zusatzbaustein Verschleiß ersetzt nach Produktdarstellung Verschleiß bzw. innere Betriebsschäden elektronischer Bauteile bis 150 EUR pro Versicherungsfall und Versicherungsjahr.'},
    {anchor:'addon:tech upgrade 10 geratewert zuschuss fur modernere teile',label:'Tech-Upgrade',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Tech',text:'Wenn im versicherten Reparaturfall technisch fortgeschrittenere Teile eingebaut werden können, beschreibt R+V einen Zuschuss von 10 % des Gerätewerts.'},
    {anchor:'addon:transport',label:'Transport',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Transport',text:'Der Baustein Transport deckt nach Produktdarstellung Schäden an versicherter Elektronik während eines privaten Transports.'},
    {anchor:'addon:unsachgemasse handhabung',label:'Unsachgemäße Handhabung',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Upgrade Unsachgemäße Handhabung',text:'Mit dem Baustein sind nach Produktdarstellung auch Schäden durch unsachgemäße Handhabung, etwa falsche Bedienung, abgesichert.'},
    {anchor:'highlight:2',label:'Fehler nach Garantie',kind:'R+V Produktseite',source:'Laptop- und Notebook-Versicherung',code:'Grundschutz · geprüft 08.08.2026',location:'Leistungen',text:'Nach Ablauf der gesetzlichen Gewährleistungsfrist bzw. Herstellergarantie, frühestens ab dem 13. Monat, nennt R+V definierte Konstruktions-, Guss-/Material-, Berechnungs-, Werkstätten- und Montagefehler als versicherte Schadenursachen.'}
  ],

  'hardware':[
    {anchor:'eligibility:0',label:'Hardwarealter Abschluss',kind:'R+V Produktseite',source:'R+V-Hardware-/Laptop-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Versicherbare Geräte',text:'Versicherbare Hardware darf bei Abschluss höchstens 36 Monate seit Neukauf alt sein.'},
    {anchor:'eligibility:1',label:'Hardwarealter Schadenfall',kind:'R+V Produktseite',source:'R+V-Hardware-/Laptop-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Versicherbare Geräte',text:'Im Schadenfall darf das Equipment höchstens 60 Monate ab Neukaufdatum alt sein.'},
    {anchor:'highlight:0',label:'Gemeinsame Versicherungssumme',kind:'R+V Produktseite',source:'R+V-Hardware-/Laptop-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ mehrere Geräte',text:'Mehrere versicherte Geräte können in einer gemeinsamen Versicherungssumme zusammengefasst werden. Der Gesamtwert der Geräte darf die vereinbarte Versicherungssumme nicht überschreiten.'},
    {anchor:'highlight:1',label:'Versicherbare Hardware',kind:'R+V Produktseite',source:'R+V-Hardware-/Laptop-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Welche Geräte sind versichert?',text:'Als versicherbar nennt R+V unter anderem Monitore/TV, Desktop-PC, Laptops/Notebooks, Spielekonsolen, Peripherie, betriebsnotwendige Hardware, Streaming-Equipment, professionelle Beleuchtung sowie Computer-Stühle und -Tische.'}
  ],

  'phv':[
    {anchor:'tariff:premium',label:'Schlüsselverlust premium',kind:'Bedingungswerk',source:'R+V Privatkunden Verbraucherinformation premium',code:'HPB 07/26',location:'Z-SCHL-01/02 · HPB S. 47–48',quote:'Schäden aus dem Abhandenkommen von fremden berufsbezogenen Schlüsseln',text:'Die premium-Bedingungen erfassen private und berufsbezogene fremde Schlüssel sowie elektronische Schließmedien. Erfasst werden insbesondere notwendige Schloss-, Schlüssel- und Sperrkosten; konkrete Höchstbeträge ergeben sich aus Versicherungsschein/Nachtrag.'},
    {anchor:'highlight:2',label:'Neuwertoption premium',kind:'Bedingungswerk',source:'R+V Privatkunden Verbraucherinformation premium',code:'HPB 07/26',location:'Neuwertentschädigung · HPB S. 56',text:'Die Neuwertentschädigung setzt unter anderem einen irreparablen Schaden, die Einhaltung des vereinbarten Sachalters und eine vorherige Zeitwertregulierung voraus; Ausschlüsse sind in derselben Klausel geregelt.'}
    ,{anchor:'highlight:2',label:'Premium-Leistungswerte',kind:'R+V Produktseite / Leistungstabelle',source:'Private Haftpflichtversicherung',code:'Tarifübersicht · geprüft 08.08.2026',location:'Neuwertersatz / Kfz-Be- und Entladeschäden',text:'Die aktuelle R+V-Tarifübersicht konkretisiert für premium den Neuwertersatz mit bis zu 10.000 EUR und Sachalter bis 2 Jahre sowie Kfz-Be-/Entladeschäden bis 10.000 EUR.'}
  ],

  'hausrat':[
    {anchor:'tariff:premium',label:'Außenversicherung',kind:'Bedingungswerk',source:'R+V Privatkunden Verbraucherinformation premium',code:'HRB 07/2026',location:'A12 · HRB S. 15–16',quote:'Außerhalb des Versicherungsorts besteht für versicherte Sachen weltweit Versicherungsschutz',text:'A12 regelt die weltweite Außenversicherung für nur vorübergehend außerhalb des Versicherungsorts befindlichen Hausrat. Dauer und Entschädigungsgrenze richten sich nach dem Versicherungsschein.'},
    {anchor:'tariff:premium',label:'Premium-Leistungswerte',kind:'R+V Produktseite / Leistungstabelle',source:'Hausratversicherung',code:'Tarifübersicht · geprüft 08.08.2026',location:'Außenversicherung / Bargeld / Versehensschutz',text:'Die aktuelle Tarifübersicht nennt für premium 12 Monate Außenversicherung bis 100.000 EUR, Bargeld bis 5.000 EUR und Versehensschutz zu Hause bis 5.000 EUR bei 500 EUR Selbstbeteiligung.'},
    {anchor:'highlight:0',label:'Hausrat und Wertsachen',kind:'Bedingungswerk',source:'R+V Privatkunden Verbraucherinformation premium',code:'HRB 07/2026',location:'A8, A18 · HRB S. 13, 23–24',text:'Zum Hausrat gehören privat genutzte Sachen des Haushalts; Wertsachen und Bargeld sind mit besonderen Entschädigungsgrenzen einbezogen. Die vereinbarten Beträge stehen im Versicherungsschein.'},
    {anchor:'highlight:0',label:'Versicherungssumme und Neuwert',kind:'R+V Produktseite / FAQ',source:'Hausratversicherung',code:'Leistungsübersicht · geprüft 08.08.2026',location:'Versicherungssumme / FAQ „Wie hoch sollte …?“',text:'R+V weist die Versicherungssumme in der Tarifübersicht für classic, comfort und premium als unbegrenzt aus. Die FAQ erläutert: Bei korrekter Angabe der Wohnfläche besteht Neuwertschutz und eine Unterversicherung wird ausgeschlossen.'},
    {anchor:'addon:hausrat auf reisen',label:'Außenversicherung / Reisen',kind:'Bedingungswerk',source:'R+V Privatkunden Verbraucherinformation premium',code:'HRB 07/2026',location:'A12 · HRB S. 15–16',text:'Der Schutz für Hausrat außerhalb der Wohnung ist über die Außenversicherung geregelt. Bei Naturgefahren bestehen innerhalb der Außenversicherung zusätzliche Einschränkungen.'}
  ],

  'pv':[
    {anchor:'highlight:0',label:'Private Photovoltaikanlagen bis 30 kWp',kind:'R+V Produktseite / Leistungstabelle',source:'R+V Photovoltaikversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Photovoltaikversicherung für Privatkunden',text:'R+V ordnet den privaten Photovoltaikschutz als Zusatzbaustein der Wohngebäudeversicherung ein und nennt für diesen Produktweg Dachanlagen bis 30 kWp.'},
    {anchor:'highlight:1',label:'Versicherbare Gefahren',kind:'R+V Produktseite / Leistungstabelle',source:'R+V Photovoltaikversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen Photovoltaik',text:'Die Produktdarstellung nennt unter anderem Sturm und Hagel, Diebstahl, Überspannung sowie Tierbiss. Maßgeblich für Umfang, Ausschlüsse und Entschädigung bleiben Tarif, Vereinbarung und Bedingungen.'},
    {anchor:'highlight:2',label:'Ertragsausfall',kind:'R+V Produktseite / Leistungstabelle',source:'R+V Photovoltaikversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Optionaler Ertragsausfall',text:'Der Ertragsausfall kann optional vereinbart werden. Die aktuelle Produktseite beschreibt eine wählbare Leistungsdauer von bis zu 180 Tagen.'}
  ],

  'recht-verkehr':[
    {anchor:'tariff:classic',label:'Verkehrs-Rechtsschutz classic',kind:'R+V Produktseite / Bedingungswerk',source:'R+V-Verkehrsrechtsschutz',code:'RSB · geprüft 08.08.2026',location:'Tarif-/Leistungsübersicht',text:'Für die classic-Stufe der PrivatPolice wird eine Versicherungssumme von 1 Mio. EUR je Rechtsschutzfall ausgewiesen; maßgeblich sind die vereinbarten RSB.'},
    {anchor:'tariff:comfort',label:'Verkehrs-Rechtsschutz comfort',kind:'R+V Produktseite / Bedingungswerk',source:'R+V-Verkehrsrechtsschutz',code:'RSB · geprüft 08.08.2026',location:'Tarif-/Leistungsübersicht',text:'Die comfort-Stufe bietet eine Versicherungssumme bis 4 Mio. EUR. Die Produktseite beschreibt außerdem weltweiten Schutz für Aufenthalte außerhalb Europas bis zu drei Jahren im tariflichen Umfang.'},
    {anchor:'highlight:0',label:'Versicherte Verkehrskonflikte',kind:'R+V Produktseite',source:'R+V-Verkehrsrechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Das Wichtigste zum Verkehrsrechtsschutz',text:'R+V nennt unter anderem Unfall, Bußgeld, Führerscheinprobleme, Fahrzeugkauf und Werkstattrechnung als typische versicherte Rechtskonflikte.'},
    {anchor:'highlight:1',label:'Kostenübernahme Verkehrsrechtsschutz',kind:'R+V Produktseite',source:'R+V-Verkehrsrechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Kostenübernahme',text:'Im versicherten Rechtsschutzfall übernimmt R+V nach Produktdarstellung gesetzliche Anwalts- und Gerichtskosten sowie tariflich Kosten für gerichtliche Gutachter, Zeugen und Kautionen.'},
    {anchor:'highlight:2',label:'Anwaltstelefon und Mediation',kind:'R+V Produktseite',source:'R+V-Verkehrsrechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Rechtsberatung am Telefon',text:'R+V bietet telefonische Rechtsberatung ohne Wartezeit und Selbstbeteiligung sowie Mediation als außergerichtliche Unterstützung im tariflichen Rahmen.'}
  ],

  'recht-beruf':[
    {anchor:'highlight:0',label:'Arbeits-Rechtsschutz',kind:'R+V Produktseite',source:'R+V-Berufsrechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Was ist versichert?',text:'Der Berufs-Rechtsschutz schützt die nichtselbstständige berufliche Tätigkeit; genannt werden unter anderem Kündigung, Abmahnung, Gehaltsforderungen und Versetzungen.'},
    {anchor:'highlight:1',label:'Aufhebungsvereinbarung',kind:'R+V Produktseite',source:'R+V-Berufsrechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'Liegt eine Aufhebungsvereinbarung vor, nennt R+V eine Kostenübernahme bis 500 EUR je Fall ohne Anrechnung auf die Selbstbeteiligung.'},
    {anchor:'highlight:2',label:'Beratungsservices Berufsrechtsschutz',kind:'R+V Produktseite',source:'R+V-Berufsrechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Vorteile',text:'R+V nennt Anwaltstelefon ohne Anrechnung auf die Selbstbeteiligung und Mediation als ergänzende Services.'},
    {anchor:'addon:spezial straf rechtsschutz',label:'Spezial-Straf-Rechtsschutz',kind:'R+V Produktseite',source:'R+V-Berufsrechtsschutz',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Rundum-Absicherung / Vorteile',text:'Spezial-Straf-Rechtsschutz wird als zubuchbarer Schutz beschrieben, etwa wenn im beruflichen Zusammenhang ein vorsätzliches Vergehen vorgeworfen wird. Der konkrete Umfang folgt den Bedingungen.'}
  ],

  'recht-immo':[
    {anchor:'highlight:0',label:'Mietvertrag und Nebenkosten',kind:'R+V Produktseite',source:'R+V-Immobilien-Rechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'R+V nennt Streitigkeiten im Zusammenhang mit Mietvertrag, Mieterhöhung, Kündigung und Nebenkostenabrechnung als versicherte Themenbereiche.'},
    {anchor:'highlight:1',label:'Schadenersatz und Steuer',kind:'R+V Produktseite',source:'R+V-Immobilien-Rechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'Die Produktdarstellung nennt Schadenersatz-Rechtsschutz bei Sachschäden rund um die Immobilie sowie Steuer-Rechtsschutz bei Konflikten mit dem Finanzamt.'},
    {anchor:'highlight:2',label:'Mediation Immobilie',kind:'R+V Produktseite',source:'R+V-Immobilien-Rechtsschutz',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'Mediation wird als außergerichtliche Lösungsoption beschrieben, beispielsweise bei Nachbarschaftskonflikten.'}
  ],

  'gewaesser':[
    {anchor:'highlight:0',label:'Eigenschäden Gewässer',kind:'R+V Produktseite / Leistungstabelle',source:'R+V-Gewässerschadenhaftpflichtversicherung',code:'classic / comfort / premium · geprüft 08.08.2026',location:'Leistungen',text:'Für Eigenschäden an unbeweglichen Sachen nennt R+V bis 10 Mio. EUR in classic und comfort sowie bis 100 Mio. EUR in premium.'},
    {anchor:'highlight:1',label:'Umweltschaden Gewässer',kind:'R+V Produktseite / Leistungstabelle',source:'R+V-Gewässerschadenhaftpflichtversicherung',code:'classic / comfort / premium · geprüft 08.08.2026',location:'Leistungen',text:'Die Umweltschadensversicherung wird mit 10 Mio. EUR in classic, 40 Mio. EUR in comfort und 100 Mio. EUR in premium ausgewiesen.'},
    {anchor:'highlight:2',label:'Rettung / Ersatzbefüllung',kind:'R+V Produktseite / Leistungstabelle',source:'R+V-Gewässerschadenhaftpflichtversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen / Ausschlüsse',text:'Rettungskosten und Ersatzbefüllung des ausgelaufenen Öltanks sind in der R+V-Leistungstabelle enthalten. Vorsätzliche Verstöße gegen Gewässerschutzvorschriften werden als nicht versichert genannt.'}
  ],

  'bauherr':[
    {anchor:'highlight:0',label:'Bauherrenhaftpflicht – Schutzumfang',kind:'R+V Produktseite / Ratgeber',source:'R+V-Bauherrenhaftpflichtversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Bauherrenhaftpflicht',text:'R+V beschreibt die Absicherung des Bauherrn und der einbezogenen Bauhelfer gegen finanzielle Folgen versicherter Personen-, Sach- und Vermögensschäden am Bau.'},
    {anchor:'highlight:1',label:'Abwehr unberechtigter Ansprüche',kind:'R+V Produktseite',source:'R+V-Bauherrenhaftpflichtversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'Unberechtigte Forderungen werden geprüft und im versicherten Umfang abgewehrt; R+V nennt ausdrücklich auch die Kosten eines erforderlichen Prozesses.'},
    {anchor:'highlight:2',label:'Abgrenzung Bauleistung',kind:'R+V Ratgeber',source:'Absicherung vor, während und nach dem Bauen',code:'R+V Bauabsicherung · geprüft 08.08.2026',location:'Bauleistungsversicherung',text:'Die Bauleistungsversicherung schützt die Bauleistung selbst gegen definierte unvorhergesehene Beschädigung oder Zerstörung und erfüllt damit einen anderen Zweck als die Bauherrenhaftpflicht.'}
  ],

  'wasserfahrzeug':[
    {anchor:'highlight:0',label:'Deckung Wasserfahrzeuge',kind:'R+V Produktseite',source:'Haftpflichtversicherung für private Wasserfahrzeuge',code:'Produktdarstellung · geprüft 08.08.2026',location:'Umfassende Leistungen',text:'Je nach Tarif nennt R+V 3 Mio., 5 Mio., 7,5 Mio. oder 10 Mio. EUR für Personen- und Sachschäden sowie 100.000 EUR für Vermögensschäden.'},
    {anchor:'highlight:1',label:'Weltweiter Bootsschutz',kind:'R+V Produktseite',source:'Haftpflichtversicherung für private Wasserfahrzeuge',code:'Produktdarstellung · geprüft 08.08.2026',location:'Geltungsbereich',text:'Die Produktseite beschreibt den Versicherungsschutz für das private Wasserfahrzeug als weltweit gültig.'},
    {anchor:'highlight:2',label:'Anspruchsprüfung Wasserfahrzeug',kind:'R+V Produktseite',source:'Haftpflichtversicherung für private Wasserfahrzeuge',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen',text:'R+V prüft, ob und in welcher Höhe Schadenersatzansprüche bestehen, und übernimmt im versicherten Umfang auch die Abwehr unberechtigter Ansprüche.'}
  ],

  'jagd':[
    {anchor:'highlight:0',label:'Deckung Jagdhaftpflicht',kind:'R+V Produktseite',source:'R+V-Jagdhaftpflichtversicherung',code:'Nichtberufsjäger · geprüft 08.08.2026',location:'Umfassende Leistungen',text:'Je nach Tarif nennt R+V 3 Mio., 5 Mio., 7,5 Mio. oder 10 Mio. EUR für Personen- und Sachschäden sowie 100.000 EUR für Vermögensschäden.'},
    {anchor:'highlight:1',label:'Jagdhunde / weltweit',kind:'R+V Produktseite',source:'R+V-Jagdhaftpflichtversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Produktvorteile',text:'R+V nennt Jagdhunde als mitversichert und beschreibt den Versicherungsschutz als weltweit gültig.'},
    {anchor:'highlight:2',label:'Versicherte jagdliche Rollen',kind:'R+V Produktseite',source:'R+V-Jagdhaftpflichtversicherung',code:'Nichtberufsjäger · geprüft 08.08.2026',location:'Zielgruppe',text:'Die Produktdarstellung nennt unter anderem private Jäger, Jagdpächter, Jagdherren/Jagdveranstalter, Jagdaufseher und Falkner als Zielgruppen des Nichtberufsjäger-Schutzes.'}
  ],

  'reitlehrer':[
    {anchor:'highlight:0',label:'Tarife Reitlehrer',kind:'R+V Produktseite / Leistungstabelle',source:'R+V-Reitlehrerhaftpflichtversicherung',code:'Standard / Erweitert · geprüft 08.08.2026',location:'Versicherungssummen und Beiträge',text:'R+V unterscheidet Standard mit 3 Mio. EUR und Erweitert mit 5 Mio. EUR für Personen-/Sachschäden; Vermögensschäden sind in beiden Varianten mit 100.000 EUR ausgewiesen. Die Beiträge unterscheiden zusätzlich zwischen neben- und hauptberuflicher Tätigkeit.'},
    {anchor:'addon:schaden an fremden beritt und ausbildungspferden',label:'Fremde Beritt-/Ausbildungspferde',kind:'R+V Produktseite',source:'R+V-Reitlehrerhaftpflichtversicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Zusatzbausteine',text:'R+V bietet einen Zusatzschutz für versicherte Schäden an fremden Beritt- und Ausbildungspferden, die dem Reitlehrer anvertraut wurden.'},
    {anchor:'addon:eigenes hilfspersonal',label:'Hilfspersonal',kind:'R+V Produktseite',source:'R+V-Reitlehrerhaftpflichtversicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Zusatzbausteine',text:'Ein Zusatzbaustein kann Haftpflichtschäden einbeziehen, die während der beruflichen Tätigkeit des eigenen Hilfspersonals entstehen.'},
    {anchor:'addon:schaden durch eigene schulpferde',label:'Eigene Schulpferde',kind:'R+V Produktseite',source:'R+V-Reitlehrerhaftpflichtversicherung',code:'Zusatzbaustein · geprüft 08.08.2026',location:'Zusatzbausteine',text:'R+V nennt einen Zusatzbaustein für Schäden, die durch eigene Schulpferde verursacht werden.'}
  ],

  'unfall':[
    {anchor:'addon:risikoplus',label:'RisikoPlus',kind:'Bedingungswerk',source:'R+V-UnfallPolice Verbraucherinformationen und Bedingungen',code:'R+V RisikoPlus',location:'RisikoPlus · Heft S. 80',quote:'um 50 %',text:'Bei Freizeitunfällen erhöht RisikoPlus die Invaliditätsleistung um 50 %, wenn der nach den Bedingungen ermittelte Invaliditätsgrad mindestens 20 % beträgt.'},
    {anchor:'addon:premiumplus',label:'PremiumPlus',kind:'Bedingungswerk',source:'R+V-UnfallPolice Verbraucherinformationen und Bedingungen',code:'R+V PremiumPlus',location:'Nr. 6 ff. · Heft S. 75–79',quote:'bis zu 50.000 EUR',text:'PremiumPlus erweitert den Schutz unter anderem um kosmetische Operationen, Unfall-Service, Sofortleistung, Kurkosten, Umbaukosten sowie weitere Unfallbegriffs- und Leistungsverbesserungen.'},
    {anchor:'addon:hilfeplus',label:'HilfePlus',kind:'Bedingungswerk',source:'R+V-UnfallPolice Verbraucherinformationen und Bedingungen',code:'R+V HilfePlus',location:'Abschnitt B Nr. 2 · Heft S. 73',quote:'insgesamt bis zu 20.000 EUR je Unfall',text:'HilfePlus umfasst Reha-Management; für vom Reha-Manager empfohlene erforderliche Maßnahmen gilt die in den Bedingungen genannte Gesamtgrenze. Hilfs- und Pflegeleistungen sind separat geregelt.'}
  ],

  'unfall-kind':[
    {anchor:'eligibility:0',label:'Kinder-Tarif Risiko-Unfall',kind:'R+V Produktseite',source:'R+V-Kinderunfallversicherung',code:'Risiko-Unfall · geprüft 08.08.2026',location:'Kinder-Tarif / Altersregelung',text:'R+V beschreibt den Kinder-Tarif der Risiko-Unfallversicherung für Alter 0 bis 17. Die Umstellung in den Erwachsenentarif erfolgt nach den beschriebenen Regeln spätestens mit 21, sofern nicht bereits vorher.'},
    {anchor:'eligibility:1',label:'Kapital-Unfall Kinder',kind:'R+V Produktseite',source:'R+V-Kinderunfallversicherung',code:'Kapital-Unfall · geprüft 08.08.2026',location:'Kapital-Unfallversicherung für Kinder',text:'Für die Kapital-Unfallversicherung nennt R+V einen Abschluss von Geburt bis Alter 14 und eine Mindestlaufzeit von zwölf Jahren; dadurch kann die Laufzeit über den 18. Geburtstag hinausreichen.'}
  ],

  'unfall-bau':[
    {anchor:'highlight:0',label:'Kapital ab 1 % Invalidität',kind:'R+V Produktübersicht',source:'R+V-Unfallversicherungen',code:'Bauherren/Bauhelfer · geprüft 08.08.2026',location:'Risiko-Unfallversicherung für Bauherren und Bauhelfer',text:'R+V nennt für diesen Produktweg eine einmalige Kapitalleistung bereits ab 1 % bedingungsgemäßer Invalidität.'},
    {anchor:'highlight:1',label:'Krankenhaustagegeld Bau',kind:'R+V Produktübersicht',source:'R+V-Unfallversicherungen',code:'Bauherren/Bauhelfer · geprüft 08.08.2026',location:'Wichtigste Vorteile',text:'Bei erforderlicher stationärer Behandlung wird nach Produktdarstellung je Behandlungstag der vereinbarte Krankenhaustagegeldbetrag geleistet.'},
    {anchor:'highlight:2',label:'Unfalltod Bau',kind:'R+V Produktübersicht',source:'R+V-Unfallversicherungen',code:'Bauherren/Bauhelfer · geprüft 08.08.2026',location:'Wichtigste Vorteile',text:'Führt der versicherte Unfall innerhalb eines Jahres zum Tod, nennt R+V die vereinbarte Todesfallleistung für Hinterbliebene.'}
  ],

  'pferd-leben':[
    {anchor:'eligibility:0',label:'Pferdealter im Versicherungsschutz',kind:'R+V Produktseite',source:'R+V-Tierlebensversicherung für Pferde',code:'Basis / Premium / Exzellent · geprüft 08.08.2026',location:'Tarife / Versicherungsdauer',text:'Die Produktdarstellung beschreibt Versicherungsschutz abhängig von der gewählten Variante bis zu einem Alter des Pferdes von 18 Jahren. Das ist kein pauschales Höchstaufnahmealter; die Abschlussvoraussetzungen sind gesondert zu prüfen.'}
  ],

  'pferd-op':[
    {anchor:'eligibility:0',label:'Höchstaufnahmealter Pferde-OP',kind:'R+V Produktseite',source:'R+V-Pferde-OP-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ / Abschluss',text:'Das Höchstaufnahmealter beträgt nach der aktuellen Produktseite 15 Jahre.'},
    {anchor:'eligibility:1',label:'Vertragslaufzeit Pferde-OP',kind:'R+V Produktseite',source:'R+V-Pferde-OP-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Vertragslaufzeit',text:'R+V nennt eine Mindestvertragslaufzeit von einem Jahr; alternativ kann eine dreijährige Laufzeit gewählt werden. Nach einem Jahr wird eine tägliche Kündigungsmöglichkeit beschrieben.'},
    {anchor:'highlight:0',label:'Wartezeiten Pferde-OP',kind:'R+V Produktseite',source:'R+V-Pferde-OP-Versicherung',code:'Basis / Premium / Exzellent · geprüft 08.08.2026',location:'Wartezeiten',text:'Für Kolik-Operationen werden fünf Tage Wartezeit in allen Varianten genannt; bei unfallbedingten Operationen entfällt die Wartezeit in Exzellent. Für weitere Operationen gelten die jeweils genannten Sonderwartezeiten.'}
  ],

  'hund-op':[
    {anchor:'eligibility:0',label:'Aufnahmealter Hunde-OP',kind:'R+V Produktseite',source:'Hunde-OP-Versicherung',code:'Basis / Premium / Exzellent · geprüft 08.08.2026',location:'Abschluss / Alter',text:'Die aktuelle R+V-Produktseite nennt eine Aufnahme bis zu einem Hundealter von acht Jahren.'},
    {anchor:'eligibility:1',label:'Kündigung nach Mindestlaufzeit',kind:'R+V Produktseite',source:'Hunde-OP-Versicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Vertragslaufzeit',text:'Nach einem Jahr Vertragslaufzeit beschreibt R+V eine tägliche Kündigungsmöglichkeit.'},
    {anchor:'highlight:1',label:'Wartezeiten Hunde-OP',kind:'Bedingungswerk',source:'Allgemeine Versicherungsbedingungen OPK Hund',code:'AVB OPKKT 2017 der VTV',location:'§ A 9 Nr. 3 · Heft S. 8',quote:'Für Schäden infolge Unfall gilt eine Wartezeit von einer Woche.',text:'Die Grundbedingungen nennen bei unfallbedingten Schäden eine Woche Wartezeit und bei sonstigen Schäden grundsätzlich einen Monat, sofern nichts Abweichendes vereinbart ist.'},
    {anchor:'highlight:1',label:'Aktuelle Tarif-Wartezeiten',kind:'R+V Produktseite / Leistungstabelle',source:'Hunde-OP-Versicherung',code:'Basis / Premium / Exzellent · geprüft 08.08.2026',location:'Selbstbeteiligung und Wartezeiten',text:'Die aktuelle Tarifübersicht weist für Unfall-OPs eine Woche in Basis und Premium sowie keine Wartezeit in Exzellent aus. Für sonstige Operationen werden in allen drei Varianten 28 Tage genannt; für einzelne Leistungsarten gelten Sonderwartezeiten.'}
  ],

  'reise-kv':[
    {anchor:'eligibility:0',label:'FernWeh Alters-/Beitragsstufen',kind:'R+V Makler-Unterlage',source:'R+V Beitragstabelle 2026 FernWeh',code:'ARED · Stand 01/2026',location:'Beitragstabelle FernWeh',text:'Für FernWeh (ARED) nennt die offizielle Beitragstabelle 10,80 EUR/Jahr für Alter 0–64 und 46,80 EUR/Jahr ab Alter 65. Das Eintrittsalter wird als Kalenderjahr minus Geburtsjahr definiert.'},
    {anchor:'eligibility:1',label:'FernWeh Familie Altersgrenze',kind:'R+V Makler-Unterlage',source:'R+V Beitragstabelle 2026 FernWeh Familie',code:'ARFD · Stand 01/2026',location:'Beitragstabelle FernWeh Familie',text:'Für FernWeh Familie nennt R+V 22,80 EUR/Jahr für Alter 0–64 und weist ausdrücklich darauf hin, dass für Personen ab 65 Jahren keine Familienversicherung möglich ist.'},
    {anchor:'highlight:0',label:'Reisedauer FernWeh',kind:'R+V Produktseite',source:'R+V-Auslandsreise-Krankenversicherung',code:'ARED / ARFD · geprüft 08.08.2026',location:'Tarifübersicht',text:'Versicherungsschutz besteht nach Produktdarstellung jeweils für die ersten 45 Tage einer Auslandsreise, unabhängig davon, wie viele Reisen im Jahr stattfinden.'},
    {anchor:'highlight:1',label:'Verlängerung FernWeh',kind:'R+V Produktseite',source:'R+V-Auslandsreise-Krankenversicherung',code:'ARED · geprüft 08.08.2026',location:'Verlängerung ab Tag 46',text:'Für den Einzeltarif ist eine Verlängerung ab dem 46. Reisetag bis maximal 730 Tage beschrieben; dafür gelten die aktuellen Verlängerungsbeiträge und Vertragsregeln.'}
  ],

  'mitglieder-kv':[
    {anchor:'tariff:mitglieder premium',label:'Mitglieder premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'M1U · PKX 07/26',location:'Tarifteil ab Heft S. 166',text:'Das aktuelle Kranken-Bedingungsheft enthält die Tarifbedingungen M1U als premium-Stufe der Mitglieder-Krankenzusatzversicherung.'},
    {anchor:'tariff:mitglieder comfort',label:'Mitglieder comfort',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'M2U · PKX 07/26',location:'Tarifteil ab Heft S. 171',text:'Das aktuelle Kranken-Bedingungsheft enthält die Tarifbedingungen M2U als comfort-Stufe der Mitglieder-Krankenzusatzversicherung.'},
    {anchor:'tariff:mitglieder classic',label:'Mitglieder classic',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'M3U · PKX 07/26',location:'Tarifteil ab Heft S. 176',text:'Das aktuelle Kranken-Bedingungsheft enthält die Tarifbedingungen M3U als classic-Stufe der Mitglieder-Krankenzusatzversicherung.'},
    {anchor:'highlight:0',label:'Aktuelle Mitglieder-Tarife',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'M1U / M2U / M3U · PKX 07/26',location:'Heft S. 166–180',text:'Die drei Mitglieder-Tarife premium, comfort und classic sind Bestandteil des aktuellen R+V-Kranken-Bedingungshefts mit Stand 01.07.2026.'}
  ],

  'pflege-pflicht':[
    {anchor:'tariff:ppn ppb',label:'Private Pflegepflicht – Tarif PP',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'Tarif PP · PPN/PPB · PKX 07/26',location:'Tarifteil ab Heft S. 345',text:'Das aktuelle Bedingungsheft führt den Tarif PP mit den Tarifstufen PPN und PPB für die private Pflegepflichtversicherung.'},
    {anchor:'highlight:0',label:'AVB/PPV 2026',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'AVB/PPV · PKX 07/26',location:'Heft ab S. 316',text:'Das Bedingungsheft enthält die aktuellen Allgemeinen Versicherungsbedingungen der privaten Pflegepflichtversicherung einschließlich Umfang, Leistungen, Pflichten und Beendigungsregeln.'},
    {anchor:'highlight:2',label:'PPV für Studenten/Schüler/Praktikanten',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'Zusatzvereinbarung · gültig ab 01.04.2026',location:'Heft S. 344',text:'Für Studenten, Fach- und Berufsfachschüler sowie Praktikanten enthält das aktuelle Bedingungsheft eine besondere Zusatzvereinbarung zur privaten Pflegepflichtversicherung.'}
  ],

  'pkv':[
    {anchor:'tariff:agil classic pro',label:'AGIL classic pro',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PKX 07/26 · CP0U–CP3U',location:'Tarifteil ab Heft S. 37',text:'AGIL classic pro ist als Primärarzttarif für ambulante, zahnärztliche und stationäre Heilbehandlung im Dreibettzimmer ohne privatärztliche stationäre Behandlung beschrieben.'},
    {anchor:'tariff:agil comfort',label:'AGIL comfort',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PKX 07/26 · MP0U–MP3U',location:'Tarifteil ab Heft S. 46',text:'AGIL comfort ist als Primärarzttarif mit ambulanten und zahnärztlichen Leistungen sowie stationärer Heilbehandlung im Zweibettzimmer und privatärztlicher Behandlung beschrieben.'},
    {anchor:'tariff:agil premium',label:'AGIL premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PKX 07/26 · TN0U–TN3U',location:'Tarifteil ab Heft S. 55',text:'AGIL premium umfasst ambulante und zahnärztliche sowie stationäre Heilbehandlung im Einbettzimmer und privatärztliche Behandlung; Details und Erstattungsgrenzen stehen im Tarifteil.'}
  ],

  'zahn':[
    {anchor:'tariff:zahn premium',label:'Zahn premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'Z1U · gültig ab 01.01.2023',location:'Nr. 2.3–2.5 · Tarifseite 1–2 / Heft S. 145–146',quote:'zu 90 %',text:'Z1U erstattet medizinisch notwendigen Zahnersatz zu 90 % unter Anrechnung von GKV- und anderen Versicherungsleistungen. In den ersten vier Kalenderjahren gilt die tarifliche Leistungsstaffel.'},
    {anchor:'tariff:zahn comfort',label:'Zahn comfort',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'Z2U · gültig ab 01.01.2023',location:'Nr. 2.3–2.5 · Tarifseite 1–2 / Heft S. 148–149',quote:'zu 70 %',text:'Z2U erstattet medizinisch notwendigen Zahnersatz zu 70 % unter Anrechnung von GKV- und anderen Versicherungsleistungen; für Kieferorthopädie und die ersten vier Kalenderjahre gelten eigene Grenzen.'},
    {anchor:'tariff:zahn classic',label:'Zahn classic',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'Z3U · gültig ab 01.01.2023',location:'Nr. 2.2 · Tarifseite 1 / Heft S. 151',text:'Z3U erstattet für erstattungsfähigen Zahnersatz den gleichen Betrag wie der von der GKV anerkannte Festzuschuss, höchstens bis zum verbleibenden erstattungsfähigen Eigenanteil.'},
    {anchor:'highlight:0',label:'Zahnstaffel comfort / premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'Z1U / Z2U',location:'Nr. 2.4 · Heft S. 145 bzw. 148',text:'Für Z1U und Z2U sind in den ersten vier Kalenderjahren 1.000 / 2.000 / 3.000 / 4.000 EUR als gestaffelte Leistungsgrenzen geregelt; ab dem fünften Jahr entfällt diese Begrenzung, ebenso bei nachweislich unfallbedingter Behandlung.'}
  ],

  'klinik':[
    {anchor:'tariff:klinik premium',label:'Klinik premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'K1U · gültig ab 01.01.2023',location:'Nr. 2.1 · Tarifseite 1 / Heft S. 131',quote:'zu 100 %',text:'K1U erstattet bei medizinisch notwendiger stationärer Behandlung unter den tariflichen Voraussetzungen Ein- oder Zweibettzimmer und gesondert berechnete wahlärztliche Leistungen zu 100 %. Honorarvereinbarungen oberhalb der GOÄ-Höchstsätze können unter den genannten Voraussetzungen erstattungsfähig sein.'},
    {anchor:'tariff:klinik comfort',label:'Klinik comfort',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'K2U · gültig ab 01.01.2025',location:'Tarifteil ab Heft S. 136',text:'K2U ist als Zusatzversicherung für stationäre Behandlung im Zweibettzimmer geregelt; die konkrete Erstattung folgt dem Tarifteil K2U.'},
    {anchor:'tariff:klinik classic',label:'Klinik classic',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'K3U · gültig ab 01.01.2025',location:'Tarifteil ab Heft S. 140',text:'K3U ist als Zusatzversicherung für stationäre Behandlung im Zweibettzimmer infolge von Unfällen geregelt. Für diesen Tarif nennt das Bedingungsheft keine Wartezeit.'}
  ],

  'agu':[
    {anchor:'tariff:kostenerstattung ambulant',label:'Kostenerstattung ambulant',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'AGU · gültig ab 01.01.2023',location:'Nr. 2.1 · Tarifseite 1 / Heft S. 121',quote:'zu 80 %',text:'Nach GKV-Vorleistung werden 80 % der erstattungsfähigen Restaufwendungen ersetzt; oberhalb von 1.000 EUR Restaufwendungen im Kalenderjahr gilt für den darüberliegenden Teil 100 %. Ohne GKV-Vorleistung sind 40 % vorgesehen.'}
  ],

  'naturmedizin':[
    {anchor:'tariff:naturmedizin',label:'NaturMedizin',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'N1U · gültig ab 01.01.2023',location:'Nr. 2 · Tarifseite 1 / Heft S. 164',quote:'zu 80 %',text:'N1U erstattet definierte ambulante Naturheilverfahren nach Vorleistungen zu 80 %. In den ersten zwei Kalenderjahren gilt maximal 400 EUR; danach maximal 2.400 EUR innerhalb von jeweils zwei Kalenderjahren.'}
  ],

  'blickcheck':[
    {anchor:'tariff:premium',label:'Blick + Check premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'BC1U · gültig ab 01.01.2023',location:'Nr. 2 · Tarifseite 1 / Heft S. 125',text:'BC1U erstattet innerhalb von jeweils zwei Kalenderjahren Sehhilfen bzw. gleichgestellte Augenlaserleistungen und ambulante Vorsorge jeweils bis 400 EUR.'},
    {anchor:'tariff:comfort',label:'Blick + Check comfort',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'BC2U',location:'Tarifteil ab Heft S. 127',text:'BC2U ist die comfort-Stufe für Sehhilfen und Vorsorge. Die im Tarifteil geregelte Grenze beträgt je Leistungsbereich 200 EUR innerhalb von zwei Kalenderjahren.'},
    {anchor:'tariff:classic',label:'Blick + Check classic',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'BC3U',location:'Tarifteil ab Heft S. 129',text:'BC3U ist die classic-Stufe für Sehhilfen und Vorsorge. Die im Tarifteil geregelte Grenze beträgt je Leistungsbereich 100 EUR innerhalb von zwei Kalenderjahren; es gelten keine tariflichen Wartezeiten.'}
  ],

  'pflege-monat':[
    {anchor:'tariff:premium',label:'PflegeVorsorge premium',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PM1 · AVB/EPV',location:'Nr. 2.1 a · Tarifseite 2 / Heft S. 266',text:'PM1 leistet in Pflegegrad 1 10 % und in Pflegegrad 2 bis 5 jeweils 100 % des vereinbarten Pflegemonatsgelds – ambulant wie vollstationär.'},
    {anchor:'tariff:comfort',label:'PflegeVorsorge comfort',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PM2 · AVB/EPV',location:'Nr. 2.1 b · Tarifseite 2 / Heft S. 266',text:'PM2 leistet ambulant 10 % / 30 % / 70 % / 100 % / 100 % für Pflegegrad 1 bis 5; vollstationär sind ab Pflegegrad 2 jeweils 100 % vorgesehen.'},
    {anchor:'tariff:classic',label:'PflegeVorsorge classic',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PM3 · AVB/EPV',location:'Nr. 2.1 c · Tarifseite 2 / Heft S. 266',text:'PM3 sieht Leistungen ab Pflegegrad 3 vor: ambulant 70 % in Pflegegrad 3 sowie 100 % in Pflegegrad 4 und 5; vollstationär jeweils 100 % in Pflegegrad 3 bis 5.'},
    {anchor:'highlight:2',label:'Familienleistung',kind:'Bedingungswerk',source:'Bedingungsheft R+V Krankenversicherung AG',code:'PM1 / PM2 / PM3 · AVB/EPV',location:'Nr. 2.2 · Tarifseite 2 / Heft S. 266',text:'Bei Eintritt des Pflegefalls mit mindestens einem minderjährigen Kind wird das tarifliche Pflegemonatsgeld verdoppelt; die Verdoppelung endet mit dem Monat, in dem das jüngste maßgebliche Kind 18 wird.'},
    {anchor:'highlight:2',label:'Beitragspause nach Geburt',kind:'R+V Produktseite',source:'Pflegemonatsgeld / R+V-PflegeVorsorge',code:'Produktübersicht · geprüft 08.08.2026',location:'Unterstützung für Familien mit Kindern',text:'Die aktuelle Produktseite beschreibt nach einer Geburt eine Option auf Beitragspause mit vollem Versicherungsschutz für bis zu zwei Jahre. Die konkrete Inanspruchnahme richtet sich nach den vertraglichen Voraussetzungen.'}
  ],

  'pflege-tag':[
    {anchor:'tariff:pflege forderbahr',label:'Pflege FörderBahr (PKB)',kind:'R+V Produktseite / Tarifinformation',source:'R+V-Pflege FörderBahr',code:'Tarif PKB · geprüft 08.08.2026',location:'Leistung und Förderung',text:'Der staatlich geförderte Tarif leistet abhängig vom Pflegegrad. Für Pflegegrad 5 nennt die Produktdarstellung mindestens 20 EUR täglich bzw. 600 EUR monatlich bei Vorliegen der Fördervoraussetzungen.'},
    {anchor:'highlight:0',label:'Staatlicher Zuschuss',kind:'R+V Produktseite / Tarifinformation',source:'R+V-Pflege FörderBahr',code:'Tarif PKB · geprüft 08.08.2026',location:'Staatliche Förderung',text:'Die aktuelle R+V-Produktseite nennt einen staatlichen Zuschuss von 5 EUR monatlich beziehungsweise 60 EUR jährlich, sofern die gesetzlichen Fördervoraussetzungen erfüllt sind.'},
    {anchor:'highlight:1',label:'Annahme ohne Gesundheitsfragen',kind:'R+V Produktseite / Tarifinformation',source:'R+V-Pflege FörderBahr',code:'Tarif PKB · geprüft 08.08.2026',location:'Voraussetzungen / Annahme',text:'R+V beschreibt den Fördertarif ohne Gesundheitsfragen, ohne Risikozuschläge und ohne krankheitsbezogene Leistungsausschlüsse. Die weiteren Zugangsvoraussetzungen des Fördertarifs sind zu beachten.'},
    {anchor:'highlight:2',label:'Leistungsstaffel nach Pflegegrad',kind:'R+V Produktseite / Tarifinformation',source:'R+V-Pflege FörderBahr',code:'Tarif PKB · geprüft 08.08.2026',location:'Leistungen nach Pflegegrad',text:'Die Produktdarstellung staffelt das vereinbarte Tagegeld für Pflegegrad 1 bis 5 mit 10 %, 30 %, 70 %, 100 % und 100 %.'},
    {anchor:'highlight:3',label:'Wartezeit',kind:'R+V Produktseite / Tarifinformation',source:'R+V-Pflege FörderBahr',code:'Tarif PKB · geprüft 08.08.2026',location:'Wartezeit',text:'Für den Fördertarif wird eine Wartezeit von fünf Jahren beschrieben; bei unfallbedingter Pflegebedürftigkeit entfällt sie nach der aktuellen Produktdarstellung.'}
  ],

  'risikoleben':[
    {anchor:'tariff:comfort',label:'Comfort-Zusatzleistungen',kind:'Bedingungswerk',source:'Allgemeine Versicherungsbedingungen R+V-Risikoversicherung',code:'1E37 · Stand 01.07.2026',location:'§ 2 und § 12 · S. 2, 11–12',quote:'höchstens 15 Jahre',text:'Comfort und premium enthalten Kinder- und Bau-Bonus. Außerdem kann die Versicherungsdauer unter den Voraussetzungen des § 12 einmalig ohne erneute Risikoprüfung um bis zu 15 Jahre verlängert werden.'},
    {anchor:'tariff:premium',label:'Premium Pflege-Bonus',kind:'Bedingungswerk',source:'Allgemeine Versicherungsbedingungen R+V-Risikoversicherung',code:'1E37 · Stand 01.07.2026',location:'§ 3 · S. 3',quote:'10 % der aktuellen Versicherungssumme',text:'Premium enthält zusätzlich den Pflege-Bonus. Bei den in § 3 definierten Voraussetzungen beträgt er bei gleichbleibender Versicherungssumme 10 % der aktuellen Versicherungssumme, höchstens 15.000 EUR.'},
    {anchor:'highlight:1',label:'Kinder- und Bau-Bonus',kind:'Bedingungswerk',source:'Allgemeine Versicherungsbedingungen R+V-Risikoversicherung',code:'1E37 · Stand 01.07.2026',location:'§ 2 · S. 2',quote:'25.000 EUR',text:'Für comfort und premium sind Kinder- und Bau-Bonus geregelt. Bei gleichbleibender Versicherungssumme beträgt jeder Bonus 25.000 EUR; jeweils gelten das definierte Ereignisfenster und die weiteren Voraussetzungen.'},
    {anchor:'highlight:2',label:'Summengrenzen ärztliche Untersuchung Leben',kind:'R+V Makler-Unterlage',source:'Ärztliche Untersuchung – Summengrenzen',code:'Stand 06/2026',location:'Tabelle Leben / BU(Z) / GFV',text:'Bis Eintrittsalter 50 nennt R+V für Leben bis 500.000 EUR Versicherungssumme ohne ärztliche Untersuchung, ab Eintrittsalter 51 bis 400.000 EUR. Bestehende Versicherungen und weitere risikierte Summen sind nach den angegebenen Regeln anzurechnen.'}
  ],

  'sterbegeld':[
    {anchor:'eligibility:0',label:'Eintrittsalter Sterbegeld',kind:'R+V Produktseite',source:'R+V-Sterbegeldversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Abschluss / Eintrittsalter',text:'R+V nennt für die Sterbegeldversicherung einen Einstieg ab Alter 40.'},
    {anchor:'eligibility:1',label:'Beitragszahldauer Sterbegeld',kind:'R+V Produktseite',source:'R+V-Sterbegeldversicherung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Beitragszahlung',text:'Die Beitragszahldauer richtet sich nach dem Eintrittsalter und beträgt laut Produktdarstellung mindestens fünf und höchstens 25 Jahre.'}
  ],

  'vermoegen-uebertrag':[
    {anchor:'highlight:0',label:'Bezugsberechtigte und Übertragung',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Darum ist Vermögensübertragung wichtig / Bezugsberechtigte',text:'Die R+V-Produktseite beschreibt die namentliche Festlegung eines oder mehrerer Bezugsberechtigter und die Möglichkeit, diese später zu ändern. Für die beschriebene Lösung ist die Begünstigung ohne Testament oder notarielle Mitwirkung gestaltbar.'},
    {anchor:'highlight:1',label:'Verfügung, Zu- und Auszahlungen',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Vorteile / So legen wir Ihr Geld an',text:'R+V hebt hervor, dass der Versicherungsnehmer weiterhin über das Vermögen verfügen kann. Die Produktdarstellung nennt sowohl Entnahmen als auch Zuzahlungen.'},
    {anchor:'highlight:2',label:'Gesundheitsfragen und Wartezeit',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Ihre Vorteile',text:'In der aktuellen Vorteilsübersicht wird die einfache Vermögensübertragung ohne Gesundheitsfragen und ohne Wartezeit beschrieben. Die konkreten Vertragsbedingungen bleiben maßgeblich.'},
    {anchor:'highlight:3',label:'Anlageausrichtung',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Diese Optionen bietet Ihnen die R+V-Vermögensübertragung',text:'Bei der sicherheitsorientierten bis flexiblen Anlage fließt laut R+V mindestens die Hälfte in sicheres Kapital. Als Alternative wird eine chancenorientierte fondsgebundene Kapitalversicherung beschrieben.'},
    {anchor:'addon:ubertragung zu festgelegtem termin',label:'Übertragung zu Termin',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Sie legen fest, wann Ihr Geld übertragen wird',text:'Für die terminbezogene Gestaltung legt der Versicherungsnehmer einen Ablauftermin fest. Die Auszahlung erfolgt nach Produktdarstellung zu diesem Termin auch dann, wenn die versicherte Person vorher verstirbt.'},
    {anchor:'addon:ubertragung im todesfall',label:'Übertragung im Todesfall',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Sie legen fest, wann Ihr Geld übertragen wird',text:'Für die Todesfallgestaltung wird die Auszahlung an die festgelegten Bezugsberechtigten mit dem Tod der versicherten Person fällig.'},
    {anchor:'addon:sicherheitsorientierte bis flexible geldanlage',label:'Sicherheitsorientierte Anlage',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Sie legen fest, wie Ihr Geld angelegt wird',text:'Bei dieser Ausrichtung fließt mindestens die Hälfte der Anlage in das sichere Kapital; die weitere Aufteilung zwischen sicherem und Chancen-Kapital kann angepasst werden.'},
    {anchor:'addon:chancenorientierte fondsgebundene geldanlage',label:'Chancenorientierte Anlage',kind:'R+V Produktseite',source:'R+V-Vermögensübertragung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Sie legen fest, wie Ihr Geld angelegt wird',text:'Als chancenorientierte Variante beschreibt R+V eine fondsgebundene Kapitalversicherung mit Auswahl aus Fonds beziehungsweise Anlagestrategien.'}
  ],

  'cashprotect':[
    {anchor:'highlight:0',label:'Flexibilität und Kündigung',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Vorteile / FAQ',text:'R+V beschreibt CashProtect als modular: Bausteine können im Rahmen der Bedingungen zu- und abgewählt sowie Absicherungshöhen und Leistungsdauern angepasst werden. Das Produkt ist monatlich kündbar.'},
    {anchor:'highlight:1',label:'Keine Gesundheitsprüfung',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'FAQ Gesundheitsprüfung',text:'Der Abschluss erfolgt ohne Gesundheitsprüfung. R+V nennt jedoch eine Ausschlussregel für bestimmte ernstliche Erkrankungen oder Unfallfolgen mit Beratung oder Behandlung in den letzten zwölf Monaten, wenn ein ursächlicher Versicherungsfall innerhalb der ersten 24 Monate eintritt.'},
    {anchor:'highlight:2',label:'Baustein Gesundheit',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Baustein Gesundheit / Warte- und Karenzzeiten',text:'Für Arbeitsunfähigkeit sind bis zu 1.000 EUR monatliche Absicherung abhängig vom Einkommen und Leistungsdauern von 6, 12 oder 24 Monaten wählbar. R+V nennt keine Wartezeit und sechs Wochen Karenzzeit.'},
    {anchor:'highlight:3',label:'Baustein Einkommen',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Baustein Einkommen / Warte- und Karenzzeiten',text:'Der Einkommensbaustein deckt Arbeitslosigkeit und Kurzarbeit mit bis zu 1.000 EUR monatlich abhängig vom Einkommen. R+V nennt 6, 12 oder 24 Monate Leistungsdauer, sechs Monate Wartezeit und einen Monat Karenzzeit.'},
    {anchor:'highlight:4',label:'Baustein Leben',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Baustein Leben / Warte- und Karenzzeiten',text:'Im Todesfallbaustein kann laut Produktseite eine Versicherungssumme bis 100.000 EUR vereinbart werden, die einmalig ausgezahlt wird. R+V nennt weder Warte- noch Karenzzeit.'},
    {anchor:'addon:gesundheit arbeitsunfahigkeit',label:'Gesundheit',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Absicherungsbausteine',text:'Der Baustein Gesundheit adressiert das Risiko Arbeitsunfähigkeit.'},
    {anchor:'addon:einkommen arbeitslosigkeit kurzarbeit',label:'Einkommen',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Absicherungsbausteine',text:'Der Baustein Einkommen adressiert Arbeitslosigkeit und Kurzarbeit.'},
    {anchor:'addon:leben todesfall',label:'Leben',kind:'R+V Produktseite',source:'R+V-CashProtect',code:'Produktdarstellung · geprüft 08.08.2026',location:'Absicherungsbausteine',text:'Der Baustein Leben adressiert den Todesfall und sieht die vereinbarte Einmalzahlung vor.'}
  ],

  'bav':[
    {anchor:'highlight:0',label:'Lebenslange Rente / Kapitaloption',kind:'R+V Produktseite',source:'Direktversicherung durch Entgeltumwandlung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Die Direktversicherung bietet Ihnen',text:'R+V beschreibt eine lebenslange garantierte Zusatzrente ab Rentenbeginn. Auf Wunsch kann statt der laufenden Rente eine einmalige Kapitalleistung vereinbart werden.'},
    {anchor:'highlight:1',label:'Möglicher Leistungsbeginn',kind:'R+V Produktseite',source:'Direktversicherung durch Entgeltumwandlung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Ab Rentenbeginn lebenslange garantierte Rente',text:'Die Produktseite nennt die zusätzliche Rente ab vollendetem 62. Lebensjahr oder mit Beginn der gesetzlichen Rentenzahlung. Maßgeblich sind die konkrete Versorgungszusage und der Vertrag.'},
    {anchor:'highlight:2',label:'Arbeitgeberwechsel',kind:'R+V Produktseite',source:'Direktversicherung durch Entgeltumwandlung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Arbeitgeberwechsel',text:'Bei Arbeitgeberwechsel beschreibt R+V die private Fortführung, die Fortführung über den neuen Arbeitgeber oder die Übertragung des aufgebauten Kapitals in dessen Versorgungseinrichtung als Möglichkeiten.'},
    {anchor:'highlight:3',label:'Steuer und Sozialabgaben',kind:'R+V Produktseite',source:'Direktversicherung durch Entgeltumwandlung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Steuer- und Sozialabgabenfreiheit',text:'R+V weist auf steuer- und sozialversicherungsrechtliche Begünstigungen innerhalb gesetzlicher Höchstgrenzen hin. Da diese Größen regelmäßig angepasst werden, sind für die Beratung die jeweils aktuellen Sozialversicherungs- und Steuerwerte zu verwenden.'},
    {anchor:'addon:berufsunfahigkeits zusatzversicherung buz',label:'BUZ',kind:'R+V Produktseite',source:'Direktversicherung durch Entgeltumwandlung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Sinnvolle Ergänzungen',text:'Zur Absicherung finanzieller Folgen einer Berufsunfähigkeit bis zum Rentenbeginn kann laut R+V eine Berufsunfähigkeits-Zusatzversicherung eingeschlossen werden.'},
    {anchor:'addon:hinterbliebenenabsicherung',label:'Hinterbliebenenschutz',kind:'R+V Produktseite',source:'Direktversicherung durch Entgeltumwandlung',code:'Produktdarstellung · geprüft 08.08.2026',location:'Sinnvolle Ergänzungen',text:'Die Produktseite nennt eine zusätzlich einschließbare Hinterbliebenenabsicherung.'}
  ],

  'kind-index':[
    {anchor:'eligibility:0',label:'Mindestbeitrag und Zuzahlung',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen / Produktdaten',text:'R+V nennt einen laufenden Beitrag ab 25 EUR monatlich und Zuzahlungen ab 500 EUR. Für Zuzahlungen gelten zusätzlich die auf der Produktseite genannten steuerlichen Höchstgrenzen.'},
    {anchor:'eligibility:1',label:'Maximale Laufzeit',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen / Gestaltung',text:'Für die Termfix-Kapitalversicherung nennt die Produktübersicht eine maximale Laufzeit von 27 Jahren.'},
    {anchor:'highlight:0',label:'Jährliche Anlagewahl',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen / Anlagestrategie',text:'Jährlich kann zwischen sicherer Verzinsung, SOMAS-Indexpartizipation und einer Turbo-Indexvariante mit 2 % Kapitaleinsatz gewählt werden.'},
    {anchor:'highlight:1',label:'Beitragsgarantie',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungen / Beitragsgarantie',text:'Die aktuelle Produktdarstellung nennt eine Beitragsgarantie von mindestens 90 % der eingezahlten Beiträge zum Laufzeitende.'},
    {anchor:'highlight:2',label:'Teilauszahlung',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Liquiditätsoption',text:'Teilauszahlungen sind mit einer Frist von einem Monat zum nächsten Monatsersten möglich. R+V nennt mindestens 1.000 EUR Auszahlungsbetrag und mindestens 2.500 EUR verbleibendes Vertragskapital.'},
    {anchor:'highlight:3',label:'Todesfallleistung',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Todesfallleistung',text:'Stirbt die versicherte Person, werden nach Produktdarstellung keine weiteren Beiträge fällig; die vereinbarte Leistung für das Kind wird zum Auszahlungstermin erbracht. R+V weist dabei auf eine vereinfachte Gesundheitsprüfung hin.'},
    {anchor:'addon:buz beitragsbefreiung',label:'BUZ Beitragsbefreiung',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Mögliche Zusatzbausteine',text:'Als möglichen Zusatzbaustein nennt die Produktübersicht die Berufsunfähigkeits-Zusatzversicherung zur Beitragsbefreiung.'},
    {anchor:'addon:indexpartizipation mit turbo',label:'Turbo-Indexpartizipation',kind:'R+V Produktseite',source:'KinderVorsorge IndexInvest',code:'Produktdarstellung · geprüft 08.08.2026',location:'Jährliche Anlagestrategie',text:'Neben sicherer Verzinsung und normaler Indexpartizipation beschreibt R+V eine Turbo-Variante mit 2 % Kapitaleinsatz und erhöhter Beteiligungsquote.'}
  ],

  'sparen-kind':[
    {anchor:'highlight:0',label:'Sparlösungen ab 25 EUR',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'AnsparKombi / KinderVorsorge',text:'Auf der Kinder-Sparübersicht nennt R+V sowohl die AnsparKombi Safe+Smart als auch KinderVorsorge IndexInvest als Lösungen, die bereits ab 25 EUR monatlich bespart werden können.'},
    {anchor:'highlight:1',label:'AnlageKombi',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'R+V-AnlageKombi Safe+Smart',text:'Die AnlageKombi wird als Einmalanlage beschrieben, bei der der Kunde das Verhältnis zwischen sicher verzinstem und chancenorientiertem Kapital selbst wählt.'},
    {anchor:'highlight:2',label:'Weitere chancenorientierte Wege',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'InvestmentKonzept / VorsorgeKonzept',text:'Die Übersicht führt zusätzlich das InvestmentKonzept Duo Invest und das R+V-VorsorgeKonzept als fonds- beziehungsweise kapitalmarktorientierte Möglichkeiten für den Vermögensaufbau für Kinder auf.'},
    {anchor:'addon:ansparkombi safe smart',label:'AnsparKombi Safe+Smart',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'R+V-AnsparKombi Safe+Smart',text:'R+V stellt die AnsparKombi als flexible Lösung für regelmäßiges monatliches Sparen dar; die Produktübersicht nennt einen Einstieg ab 25 EUR monatlich.'},
    {anchor:'addon:anlagekombi safe smart',label:'AnlageKombi Safe+Smart',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'R+V-AnlageKombi Safe+Smart',text:'Die AnlageKombi ist in diesem Beratungsweg die auf eine Einmalzahlung ausgerichtete Safe+Smart-Lösung.'},
    {anchor:'addon:kindervorsorge indexinvest',label:'KinderVorsorge IndexInvest',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'R+V KinderVorsorge IndexInvest',text:'KinderVorsorge IndexInvest kombiniert regelmäßigen Kapitalaufbau mit jährlich wählbarer sicherer Verzinsung oder Indexbeteiligung.'},
    {anchor:'addon:investmentkonzept duo invest',label:'InvestmentKonzept Duo Invest',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'R+V-InvestmentKonzept Duo Invest',text:'Duo Invest wird als flexible, chancenorientierte Vorsorgelösung mit professionell gemanagten Anlagestrategien dargestellt.'},
    {anchor:'addon:r v vorsorgekonzept',label:'R+V-VorsorgeKonzept',kind:'R+V Produktseite',source:'Sparen für Kinder',code:'Produktübersicht · geprüft 08.08.2026',location:'R+V-VorsorgeKonzept',text:'Das VorsorgeKonzept ist eine fondsgebundene Rentenversicherung mit flexibler Beitragsgestaltung für den langfristigen Vermögensaufbau.'}
  ],

  'anlage':[
    {anchor:'eligibility:0',label:'Mindestanlage AnlageKombi',kind:'R+V Produktübersicht',source:'R+V Private Rentenversicherung / AnlageKombi Safe+Smart',code:'Produktdarstellung · geprüft 08.08.2026',location:'AnlageKombi / Einmalbeitrag',text:'Die aktuelle R+V-Altersvorsorgeübersicht beschreibt die AnlageKombi als Einmalanlage ab 5.000 EUR.'}
  ],

  'restschuld':[
    {anchor:'highlight:0',label:'Finanzierung und Laufzeit',kind:'R+V Produktseite / Leistungstabelle',source:'RatenschutzPolice: Die Restschuldversicherung der R+V',code:'Produktdarstellung · geprüft 08.08.2026',location:'Produktmerkmale',text:'R+V nennt für die RatenschutzPolice Finanzierungen bis 100.000 EUR. Die Versicherungsdauer orientiert sich an der Kreditlaufzeit und ist auf höchstens zehn Jahre begrenzt.'},
    {anchor:'highlight:1',label:'Wartezeit und Gesundheitsfragen',kind:'R+V Produktseite / Leistungstabelle',source:'RatenschutzPolice: Die Restschuldversicherung der R+V',code:'Produktdarstellung · geprüft 08.08.2026',location:'Abschluss / Wartezeiten',text:'Die Produktdarstellung nennt keine Gesundheitsfragen beim Abschluss und eine dreimonatige Wartezeit für Arbeitslosigkeit, Kurzarbeit und Scheidung. Weitere Voraussetzungen sind tarifabhängig.'},
    {anchor:'highlight:2',label:'Leistung nach versichertem Risiko',kind:'R+V Produktseite / Leistungstabelle',source:'RatenschutzPolice: Die Restschuldversicherung der R+V',code:'Produktdarstellung · geprüft 08.08.2026',location:'Leistungsübersicht',text:'Je nach eingeschlossenem Risiko nennt die Produktseite monatliche Leistungen bis 2.500 EUR bei Arbeitslosigkeit/Kurzarbeit oder Arbeitsunfähigkeit, eine Scheidungsleistung bis 15.000 EUR und bei Tod 110 % der aktuellen versicherten Summe.'}
  ],

  'bu':[
    {anchor:'tariff:classic',label:'BU classic – Leistungsbeginn',kind:'R+V Produktseite / AVB-Verweis',source:'R+V Berufsunfähigkeitsversicherung',code:'BV29 · AVB-Stand 01.04.2026',location:'Leistungstabelle der Produktseite',text:'R+V weist für classic die BU-Rente nach 18 Monaten aus. Die Produktseite nennt ausdrücklich BV29 mit AVB-Stand 01.04.2026 als maßgebliche Bedingungsgrundlage.'},
    {anchor:'tariff:comfort',label:'BU comfort – Leistungsbeginn',kind:'R+V Produktseite / AVB-Verweis',source:'R+V Berufsunfähigkeitsversicherung',code:'BV30 · AVB-Stand 01.04.2026',location:'Leistungstabelle der Produktseite',text:'R+V weist für comfort die rückwirkende Zahlung ab Beginn der bedingungsgemäßen Berufsunfähigkeit aus; BV30, Stand 01.04.2026, ist als maßgebliche AVB genannt.'},
    {anchor:'tariff:premium',label:'BU premium – Leistungsbeginn',kind:'R+V Produktseite / AVB-Verweis',source:'R+V Berufsunfähigkeitsversicherung',code:'BV31 · AVB-Stand 01.04.2026',location:'Leistungstabelle der Produktseite',text:'R+V weist für premium die rückwirkende Zahlung ab Beginn der bedingungsgemäßen Berufsunfähigkeit aus; BV31, Stand 01.04.2026, ist als maßgebliche AVB genannt.'},
    {anchor:'highlight:1',label:'50 % / Prognose / abstrakte Verweisung',kind:'R+V Produktseite / AVB-Verweis',source:'R+V Berufsunfähigkeitsversicherung',code:'BV29 / BV30 / BV31 · AVB-Stand 01.04.2026',location:'Produktübersicht und FAQ',text:'Die R+V-Produktseite nennt volle BU-Rente ab 50 % Berufsunfähigkeit, einen Prognosezeitraum von sechs Monaten und den Verzicht auf abstrakte Verweisung. Die vollständigen Definitionen bleiben den jeweiligen AVB vorbehalten.'},
    {anchor:'highlight:3',label:'Summengrenzen ärztliche Untersuchung BU/GFV',kind:'R+V Makler-Unterlage',source:'Ärztliche Untersuchung – Summengrenzen',code:'Stand 06/2026',location:'Tabelle Leben / BU(Z) / GFV',text:'R+V nennt bis 36.000 EUR jährliche BU(Z)-/GFV-Rente als Grenze ohne ärztliche Untersuchung. Ab 36.001 EUR sind die in der Tabelle genannten zusätzlichen Untersuchungen und Einkommensnachweise vorgesehen; bestehende Absicherungen sind nach den Regeln anzurechnen.'}
  ],

  'du':[
    {anchor:'eligibility:0',label:'BU-Startphase Beamte',kind:'R+V Produktseite / Makler-Unterlage',source:'R+V Dienstunfähigkeitsabsicherung',code:'Produktdarstellung 2026',location:'Einsteiger-SBU / BU-Start',text:'Für Beamtenanwärter beschreibt R+V eine individuell wählbare Startphase von zwei bis zehn Jahren. Die konkreten Vertragsvoraussetzungen ergeben sich aus dem gewählten BU-/DU-Tarif.'},
    {anchor:'highlight:2',label:'Echte und spezielle DU-Klausel',kind:'R+V Produktseite',source:'R+V-Dienstunfähigkeitsversicherung',code:'BV29 / BV30 / BV31 · Stand 01.04.2026',location:'DU-Klauseln',text:'R+V beschreibt eine echte vollständige DU-Klausel sowie eine spezielle DU-/Vollzugsdienstklausel für die erfassten Beamtengruppen. Maßgeblich ist die vereinbarte Klausel im Vertrag.'},
    {anchor:'highlight:3',label:'Beitragsstundung BU/DU',kind:'R+V Produktseite / Makler-Unterlage',source:'R+V Dienstunfähigkeitsabsicherung',code:'Stand 2026',location:'Zahlungsschwierigkeiten',text:'R+V beschreibt eine zinslose Beitragsstundung bis zu 24 Monaten bei fortbestehendem BU-Schutz, sofern die tariflichen Voraussetzungen erfüllt sind.'}
  ],

  'schueler-bu':[
    {anchor:'eligibility:0',label:'Mindestalter Schüler-BU',kind:'R+V Produktseite / Makler-Unterlage',source:'R+V BU-Versicherung für Schüler',code:'Stand 05/2026',location:'Echter BU-Schutz für Schüler',text:'Der Abschluss ist ab Alter 10 beziehungsweise ab der 5. Klasse möglich.'},
    {anchor:'eligibility:1',label:'Endalter Schüler-BU',kind:'R+V Makler-Unterlage',source:'BU-Versicherung für Schüler',code:'Stand 05/2026',location:'BU-Schutz bis 67',text:'Die aktuelle R+V-Maklerunterlage nennt für Schüler einen möglichen BU-Schutz bis maximal zum 67. Lebensjahr.'},
    {anchor:'eligibility:2',label:'Maximale anfängliche Schüler-BU-Rente',kind:'R+V Makler-Unterlage',source:'BU-Versicherung für Schüler',code:'Stand 05/2026',location:'Rentenhöhe',text:'Für Schüler der gymnasialen Oberstufe nennt R+V eine anfängliche BU-Rente bis 1.500 EUR monatlich.'},
    {anchor:'highlight:1',label:'AU-Leistung Schüler-BU',kind:'R+V Makler-Unterlage',source:'BU-Versicherung für Schüler',code:'Stand 05/2026',location:'Optionale Leistung bei Krankschreibung',text:'Bei mindestens sechs Monaten ununterbrochener fachärztlich bescheinigter Arbeitsunfähigkeit können mit der optionalen AU-Leistung unter den Voraussetzungen bis zu 36 Monate Leistungen erbracht werden.'},
    {anchor:'highlight:2',label:'Nachversicherung Berufseinstieg',kind:'R+V Makler-Unterlage',source:'BU-Versicherung für Schüler',code:'Stand 05/2026',location:'Zukunftssichere BU-Rentenhöhe',text:'Nach Aufnahme der beruflichen Tätigkeit kann die Rente bei den beschriebenen Ereignissen ohne erneute Risikoprüfung auf bis zu 80 % des Nettoeinkommens erhöht werden, in der Unterlage begrenzt auf 2.500 EUR monatlich bzw. 30.000 EUR Jahresrente.'}
  ]
};
